// Expanded city data for missing destinations
// This file adds all missing global cities to the database

import { CityInfo } from './cities';

export const expandedCityData: Record<string, CityInfo> = {
  // === TÜRKİYE - EKSİK ŞEHİRLER ===
  'ankara': {
    slug: 'ankara',
    name: 'Ankara',
    nameEn: 'Ankara',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['ESB'],
    description: 'Ankara, Türkiye\'nin başkenti ve ikinci büyük şehri. Anıtkabir, kale ve müzeleriyle tarihi zenginlik, modern başkent atmosferi ve Anadolu kültürünün merkezi.',
    highlights: ['Anıtkabir', 'Ankara Kalesi', 'Anadolu Medeniyetleri Müzesi', 'Kocatepe Camii', 'Atatürk Orman Çiftliği'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '5.7 milyon',
    image: 'https://images.unsplash.com/photo-1569230516306-5a8cb5586399?w=1200&h=600&fit=crop',
  },
  'trabzon': {
    slug: 'trabzon',
    name: 'Trabzon',
    nameEn: 'Trabzon',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['TZX'],
    description: 'Trabzon, Karadeniz\'in incisi. Sümela Manastırı, yaylalar, muhteşem doğası ve eşsiz mutfağıyla Türkiye\'nin en otantik şehirlerinden biri.',
    highlights: ['Sümela Manastırı', 'Uzungöl', 'Ayasofya Müzesi', 'Boztepe', 'Trabzon Kalesi'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '810 bin',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1200&h=600&fit=crop',
  },
  'gaziantep': {
    slug: 'gaziantep',
    name: 'Gaziantep',
    nameEn: 'Gaziantep',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['GZT'],
    description: 'Gaziantep, Türkiye\'nin gastronomi başkenti. UNESCO yaratıcı şehir ağına dahil, dünyaca ünlü baklavası, kebapları ve zengin mutfak kültürüyle tanınır.',
    highlights: ['Zeugma Mozaik Müzesi', 'Gaziantep Kalesi', 'Bakırcılar Çarşısı', 'Antep Mutfağı', 'Tarihi Hanlar'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Kasım',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '2.1 milyon',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=600&fit=crop',
  },
  'konya': {
    slug: 'konya',
    name: 'Konya',
    nameEn: 'Konya',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['KYA'],
    description: 'Konya, Mevlana\'nın şehri ve Selçuklu başkenti. Mevlana Müzesi, Sema törenleri ve derin manevi atmosferiyle Türkiye\'nin kültürel kalbi.',
    highlights: ['Mevlana Müzesi', 'Alaeddin Camii', 'Karatay Medresesi', 'Sille', 'Çatalhöyük'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Aralık',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '2.3 milyon',
    image: 'https://images.unsplash.com/photo-1588668214544-4a9b7e2f0f03?w=1200&h=600&fit=crop',
  },
  'dalaman': {
    slug: 'dalaman',
    name: 'Dalaman',
    nameEn: 'Dalaman',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['DLM'],
    description: 'Dalaman, Türkiye\'nin güneybatısında yer alan plaj destinasyonu. Fethiye, Marmaris ve Ölüdeniz\'e ulaşım kapısı, turkuaz koylar ve antik kalıntılarla dolu.',
    highlights: ['Ölüdeniz', 'Fethiye', 'Saklıkent Kanyonu', 'Kayaköy', 'Dalyan'],
    bestTimeToVisit: 'Mayıs - Ekim',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '140 bin',
    image: 'https://images.unsplash.com/photo-1519451241324-20b4ea2c4220?w=1200&h=600&fit=crop',
  },
  'adana': {
    slug: 'adana',
    name: 'Adana',
    nameEn: 'Adana',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['ADA'],
    description: 'Adana, Türkiye\'nin beşinci büyük şehri ve Çukurova\'nın kalbi. Dünyaca ünlü kebabı, Taşköprü ve zengin tarım alanlarıyla güney Türkiye\'nin merkezi.',
    highlights: ['Taşköprü', 'Sabancı Merkez Camii', 'Adana Kebabı', 'Seyhan Baraj Gölü', 'Arkeoloji Müzesi'],
    bestTimeToVisit: 'Mart - Mayıs, Ekim - Kasım',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '2.2 milyon',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1200&h=600&fit=crop',
  },

  // === AVRUPA - EKSİK ŞEHİRLER ===
  'malaga': {
    slug: 'malaga',
    name: 'Malaga',
    nameEn: 'Malaga',
    country: 'İspanya',
    countryCode: 'ES',
    airportCodes: ['AGP'],
    description: 'Malaga, Costa del Sol\'un kalbi ve Picasso\'nun doğum yeri. Güneşli plajları, canlı gece hayatı ve zengin kültürel mirası ile İspanya\'nın en popüler tatil destinasyonlarından biri.',
    highlights: ['Picasso Müzesi', 'Alcazaba', 'Malaga Katedrali', 'Muelle Uno', 'Gibralfaro Kalesi'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'İspanyolca',
    population: '580 bin',
    image: 'https://images.unsplash.com/photo-1585211969224-3e992986159d?w=1200&h=600&fit=crop',
  },
  'valencia': {
    slug: 'valencia',
    name: 'Valencia',
    nameEn: 'Valencia',
    country: 'İspanya',
    countryCode: 'ES',
    airportCodes: ['VLC'],
    description: 'Valencia, İspanya\'nın üçüncü büyük şehri ve paella\'nın doğum yeri. Sanat ve Bilim Şehri, tarihi merkez ve muhteşem plajlarıyla modern ve gelenekselin buluştuğu şehir.',
    highlights: ['Sanat ve Bilim Şehri', 'La Lonja', 'Turia Parkı', 'Merkez Pazarı', 'Malvarrosa Plajı'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'İspanyolca, Valencia dili',
    population: '800 bin',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=600&fit=crop',
  },
  'sevilla': {
    slug: 'sevilla',
    name: 'Sevilla',
    nameEn: 'Seville',
    country: 'İspanya',
    countryCode: 'ES',
    airportCodes: ['SVQ'],
    description: 'Sevilla, Endülüs\'ün başkenti ve flamenko\'nun doğum yeri. Alcázar sarayı, gotik katedral ve canlı tapas kültürüyle İspanya\'nın en romantik şehirlerinden biri.',
    highlights: ['Real Alcázar', 'Sevilla Katedrali', 'Plaza de España', 'Barrio Santa Cruz', 'Metropol Parasol'],
    bestTimeToVisit: 'Mart - Mayıs, Eylül - Kasım',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'İspanyolca',
    population: '690 bin',
    image: 'https://images.unsplash.com/photo-1541394748423-8e63eeeb7a14?w=1200&h=600&fit=crop',
  },
  'napoli': {
    slug: 'napoli',
    name: 'Napoli',
    nameEn: 'Naples',
    country: 'İtalya',
    countryCode: 'IT',
    airportCodes: ['NAP'],
    description: 'Napoli, güney İtalya\'nın kalbi ve pizza\'nın doğum yeri. Vezüv yanardağı, Pompeii kalıntıları ve otantik İtalyan sokak yaşamıyla kaotik ama büyüleyici bir şehir.',
    highlights: ['Pompeii', 'Vezüv', 'Napoli Pizza', 'Castel dell\'Ovo', 'Arkeoloji Müzesi'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'İtalyanca',
    population: '960 bin',
    image: 'https://images.unsplash.com/photo-1516483638261-f4dbaf036963?w=1200&h=600&fit=crop',
  },
  'nice': {
    slug: 'nice',
    name: 'Nice',
    nameEn: 'Nice',
    country: 'Fransa',
    countryCode: 'FR',
    airportCodes: ['NCE'],
    description: 'Nice, Fransız Rivierası\'nın incisi. Promenade des Anglais, turkuaz Akdeniz suları ve zarif yaşam tarzıyla Avrupa\'nın en şık tatil destinasyonlarından biri.',
    highlights: ['Promenade des Anglais', 'Eski Nice', 'Castle Hill', 'Cours Saleya Pazarı', 'Matisse Müzesi'],
    bestTimeToVisit: 'Mayıs - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'Fransızca',
    population: '340 bin',
    image: 'https://images.unsplash.com/photo-1491166617655-0723a0999cfc?w=1200&h=600&fit=crop',
  },
  'lyon': {
    slug: 'lyon',
    name: 'Lyon',
    nameEn: 'Lyon',
    country: 'Fransa',
    countryCode: 'FR',
    airportCodes: ['LYS'],
    description: 'Lyon, Fransa\'nın gastronomi başkenti ve UNESCO Dünya Mirası. İpek dokuma tarihi, traboule geçitleri ve dünyaca ünlü mutfağıyla Paris\'e alternatif kültür merkezi.',
    highlights: ['Vieux Lyon', 'Fourvière Tepesi', 'Les Halles Paul Bocuse', 'Traboules', 'Confluence Müzesi'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'Fransızca',
    population: '520 bin',
    image: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=1200&h=600&fit=crop',
  },
  'bruksel': {
    slug: 'bruksel',
    name: 'Brüksel',
    nameEn: 'Brussels',
    country: 'Belçika',
    countryCode: 'BE',
    airportCodes: ['BRU'],
    description: 'Brüksel, Avrupa Birliği\'nin başkenti ve çikolata cenneti. Grand Place, Atomium ve dünyaca ünlü Belçika birasıyla tarih, siyaset ve gastronominin buluştuğu şehir.',
    highlights: ['Grand Place', 'Atomium', 'Manneken Pis', 'Belçika Çikolatası', 'AB Kurumları'],
    bestTimeToVisit: 'Nisan - Eylül',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'Fransızca, Flamanca',
    population: '1.2 milyon',
    image: 'https://images.unsplash.com/photo-1559113202-c916b8e44373?w=1200&h=600&fit=crop',
  },
  'zurich': {
    slug: 'zurich',
    name: 'Zürih',
    nameEn: 'Zurich',
    country: 'İsviçre',
    countryCode: 'CH',
    airportCodes: ['ZRH'],
    description: 'Zürih, İsviçre\'nin en büyük şehri ve finans merkezi. Alp manzaraları, kristal berraklığında göl, mükemmel altyapı ve yüksek yaşam kalitesiyle Avrupa\'nın en yaşanabilir şehri.',
    highlights: ['Zürih Gölü', 'Bahnhofstrasse', 'Eski Şehir', 'Kunsthaus', 'Üetliberg'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+1',
    currency: 'İsviçre Frangı (CHF)',
    language: 'Almanca',
    population: '430 bin',
    image: 'https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=1200&h=600&fit=crop',
  },
  'cenevre': {
    slug: 'cenevre',
    name: 'Cenevre',
    nameEn: 'Geneva',
    country: 'İsviçre',
    countryCode: 'CH',
    airportCodes: ['GVA'],
    description: 'Cenevre, BM Avrupa merkezi ve uluslararası diplomasinin başkenti. Cenevre Gölü, Jet d\'Eau çeşmesi ve lüks saat markalarıyla kozmopolit bir İsviçre şehri.',
    highlights: ['Jet d\'Eau', 'Birleşmiş Milletler', 'Eski Şehir', 'Cenevre Gölü', 'CERN'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+1',
    currency: 'İsviçre Frangı (CHF)',
    language: 'Fransızca',
    population: '200 bin',
    image: 'https://images.unsplash.com/photo-1573108724029-4c46571d6490?w=1200&h=600&fit=crop',
  },
  'krakow': {
    slug: 'krakow',
    name: 'Krakow',
    nameEn: 'Krakow',
    country: 'Polonya',
    countryCode: 'PL',
    airportCodes: ['KRK'],
    description: 'Krakow, Polonya\'nın kültür başkenti ve eski kraliyet şehri. Wawel Kalesi, tarihi Yahudi mahallesi Kazimierz ve yakınlardaki Auschwitz ile derin tarihi mirasıyla öne çıkar.',
    highlights: ['Wawel Kalesi', 'Rynek Główny', 'Kazimierz', 'St. Mary\'s Bazilikası', 'Wieliczka Tuz Madeni'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Polonya Zlotisi (PLN)',
    language: 'Lehçe',
    population: '780 bin',
    image: 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=1200&h=600&fit=crop',
  },
  'varsova': {
    slug: 'varsova',
    name: 'Varşova',
    nameEn: 'Warsaw',
    country: 'Polonya',
    countryCode: 'PL',
    airportCodes: ['WAW'],
    description: 'Varşova, Polonya\'nın başkenti ve modern Avrupa\'nın yükselen yıldızı. İkinci Dünya Savaşı\'ndan yeniden inşa edilen eski şehir, canlı startup ekosistemi ve zengin kültürel yaşam.',
    highlights: ['Eski Şehir', 'Kraliyet Sarayı', 'POLIN Müzesi', 'Łazienki Parkı', 'Praga Mahallesi'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+1',
    currency: 'Polonya Zlotisi (PLN)',
    language: 'Lehçe',
    population: '1.8 milyon',
    image: 'https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=1200&h=600&fit=crop',
  },
  'oslo': {
    slug: 'oslo',
    name: 'Oslo',
    nameEn: 'Oslo',
    country: 'Norveç',
    countryCode: 'NO',
    airportCodes: ['OSL'],
    description: 'Oslo, Norveç\'in başkenti ve fiyort kenarındaki modern metropol. Viking müzeleri, Nobel Barış Ödülü ve çarpıcı İskandinav mimarisiyle kuzey Avrupa\'nın en yeşil şehri.',
    highlights: ['Vigeland Parkı', 'Opera Binası', 'Viking Müzesi', 'Munch Müzesi', 'Akershus Kalesi'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+1',
    currency: 'Norveç Kronu (NOK)',
    language: 'Norveççe',
    population: '700 bin',
    image: 'https://images.unsplash.com/photo-1513622790541-eaa84d356909?w=1200&h=600&fit=crop',
  },
  'helsinki': {
    slug: 'helsinki',
    name: 'Helsinki',
    nameEn: 'Helsinki',
    country: 'Finlandiya',
    countryCode: 'FI',
    airportCodes: ['HEL'],
    description: 'Helsinki, Finlandiya\'nın başkenti ve İskandinav tasarımının merkezi. Art Nouveau mimarisi, sauna kültürü ve Baltık Denizi manzaralarıyla modern kuzey yaşamının simgesi.',
    highlights: ['Suomenlinna', 'Senate Meydanı', 'Temppeliaukio Kilisesi', 'Market Meydanı', 'Design District'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+2',
    currency: 'Euro (EUR)',
    language: 'Fince, İsveççe',
    population: '660 bin',
    image: 'https://images.unsplash.com/photo-1538332576228-eb5b4c4de6f5?w=1200&h=600&fit=crop',
  },
  'dublin': {
    slug: 'dublin',
    name: 'Dublin',
    nameEn: 'Dublin',
    country: 'İrlanda',
    countryCode: 'IE',
    airportCodes: ['DUB'],
    description: 'Dublin, İrlanda\'nın başkenti ve edebiyat mirası. Trinity College, Temple Bar ve Guinness ile geleneksel İrlanda pub kültürünün kalbi.',
    highlights: ['Trinity College', 'Temple Bar', 'Guinness Storehouse', 'St. Patrick\'s Katedrali', 'Phoenix Park'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+0',
    currency: 'Euro (EUR)',
    language: 'İngilizce, İrlandaca',
    population: '550 bin',
    image: 'https://images.unsplash.com/photo-1549918864-48ac978761a4?w=1200&h=600&fit=crop',
  },
  'selanik': {
    slug: 'selanik',
    name: 'Selanik',
    nameEn: 'Thessaloniki',
    country: 'Yunanistan',
    countryCode: 'GR',
    airportCodes: ['SKG'],
    description: 'Selanik, Yunanistan\'ın ikinci büyük şehri ve kuzey Ege\'nin kültür merkezi. Osmanlı ve Bizans mirası, canlı gece hayatı ve lezzetli Yunan mutfağıyla tanınır.',
    highlights: ['Beyaz Kule', 'Aristotelous Meydanı', 'Rotonda', 'Ladadika', 'Ano Poli'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+2',
    currency: 'Euro (EUR)',
    language: 'Yunanca',
    population: '320 bin',
    image: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200&h=600&fit=crop',
  },
  'sofya': {
    slug: 'sofya',
    name: 'Sofya',
    nameEn: 'Sofia',
    country: 'Bulgaristan',
    countryCode: 'BG',
    airportCodes: ['SOF'],
    description: 'Sofya, Bulgaristan\'ın başkenti ve Balkanların en uygun fiyatlı başkenti. Vitosha Dağı manzaraları, Roma kalıntıları ve zengin gece hayatıyla keşfedilmeyi bekleyen şehir.',
    highlights: ['Alexander Nevsky Katedrali', 'Vitosha Dağı', 'Serdika Kalıntıları', 'Boyana Kilisesi', 'Ulusal Tarih Müzesi'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+2',
    currency: 'Bulgar Levası (BGN)',
    language: 'Bulgarca',
    population: '1.3 milyon',
    image: 'https://images.unsplash.com/photo-1555990538-f78fbc765d7a?w=1200&h=600&fit=crop',
  },
  'bukres': {
    slug: 'bukres',
    name: 'Bükreş',
    nameEn: 'Bucharest',
    country: 'Romanya',
    countryCode: 'RO',
    airportCodes: ['OTP'],
    description: 'Bükreş, Romanya\'nın başkenti ve "Doğunun Paris\'i". Devasa Parlamento Sarayı, Art Deco binaları ve canlı gece hayatıyla Balkanların en dinamik şehirlerinden biri.',
    highlights: ['Parlamento Sarayı', 'Eski Şehir', 'Köy Müzesi', 'Herastrau Parkı', 'Athenaeum'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+2',
    currency: 'Romen Leyi (RON)',
    language: 'Romence',
    population: '1.9 milyon',
    image: 'https://images.unsplash.com/photo-1584638917227-7a0ad2e4f2e8?w=1200&h=600&fit=crop',
  },
  'riga': {
    slug: 'riga',
    name: 'Riga',
    nameEn: 'Riga',
    country: 'Letonya',
    countryCode: 'LV',
    airportCodes: ['RIX'],
    description: 'Riga, Baltık\'ın en büyük şehri ve Art Nouveau başkenti. UNESCO korumalı eski şehir, şık kafeler ve canlı gece hayatıyla Baltık turlarının merkezi.',
    highlights: ['Eski Riga', 'Art Nouveau Bölgesi', 'Dome Katedrali', 'Merkez Pazarı', 'Özgürlük Anıtı'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+2',
    currency: 'Euro (EUR)',
    language: 'Letçe',
    population: '630 bin',
    image: 'https://images.unsplash.com/photo-1571158186853-1d8c1d3d3c82?w=1200&h=600&fit=crop',
  },
  'tallinn': {
    slug: 'tallinn',
    name: 'Tallinn',
    nameEn: 'Tallinn',
    country: 'Estonya',
    countryCode: 'EE',
    airportCodes: ['TLL'],
    description: 'Tallinn, Estonya\'nın dijital başkenti ve ortaçağ masalı. UNESCO korumalı eski şehir surları, modern teknoloji kültürü ve kuzey Avrupa\'nın en iyi korunmuş ortaçağ merkezi.',
    highlights: ['Eski Şehir', 'Toompea Kalesi', 'Alexander Nevsky Katedrali', 'Telliskivi', 'Kadriorg Parkı'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+2',
    currency: 'Euro (EUR)',
    language: 'Estonca',
    population: '440 bin',
    image: 'https://images.unsplash.com/photo-1565791380713-1756b9a05343?w=1200&h=600&fit=crop',
  },
  'vilnius': {
    slug: 'vilnius',
    name: 'Vilnius',
    nameEn: 'Vilnius',
    country: 'Litvanya',
    countryCode: 'LT',
    airportCodes: ['VNO'],
    description: 'Vilnius, Litvanya\'nın başkenti ve Baltık\'ın barok incisi. UNESCO korumalı en büyük barok eski şehrinden biri, bağımsız Užupis Cumhuriyeti ve yeşil alanlarla dolu.',
    highlights: ['Eski Şehir', 'Gediminas Kulesi', 'Užupis', 'Gates of Dawn', 'Katedra Meydanı'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+2',
    currency: 'Euro (EUR)',
    language: 'Litvanca',
    population: '580 bin',
    image: 'https://images.unsplash.com/photo-1567000833067-a0e0a48c7316?w=1200&h=600&fit=crop',
  },

  // === ASYA - EKSİK ŞEHİRLER ===
  'osaka': {
    slug: 'osaka',
    name: 'Osaka',
    nameEn: 'Osaka',
    country: 'Japonya',
    countryCode: 'JP',
    airportCodes: ['KIX'],
    description: 'Osaka, Japonya\'nın mutfak başkenti ve eğlence merkezi. Osaka Kalesi, Dotonbori ışıkları ve sokak yemekleriyle Tokyo\'ya samimi alternatif.',
    highlights: ['Osaka Kalesi', 'Dotonbori', 'Universal Studios Japan', 'Shinsekai', 'Kuromon Pazarı'],
    bestTimeToVisit: 'Mart - Mayıs, Ekim - Kasım',
    timezone: 'UTC+9',
    currency: 'Yen (JPY)',
    language: 'Japonca',
    population: '2.7 milyon',
    image: 'https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1200&h=600&fit=crop',
  },
  'kyoto': {
    slug: 'kyoto',
    name: 'Kyoto',
    nameEn: 'Kyoto',
    country: 'Japonya',
    countryCode: 'JP',
    airportCodes: ['KIX'],
    description: 'Kyoto, Japonya\'nın eski imparatorluk başkenti. 2000\'den fazla tapınak, geisha bölgeleri ve geleneksel çay evleriyle otantik Japon kültürünün kalbi.',
    highlights: ['Fushimi Inari', 'Kinkaku-ji', 'Arashiyama', 'Gion', 'Kiyomizu-dera'],
    bestTimeToVisit: 'Mart - Mayıs, Ekim - Kasım',
    timezone: 'UTC+9',
    currency: 'Yen (JPY)',
    language: 'Japonca',
    population: '1.5 milyon',
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1200&h=600&fit=crop',
  },
  'phuket': {
    slug: 'phuket',
    name: 'Phuket',
    nameEn: 'Phuket',
    country: 'Tayland',
    countryCode: 'TH',
    airportCodes: ['HKT'],
    description: 'Phuket, Tayland\'ın en büyük adası ve plaj cenneti. Patong gece hayatı, turkuaz koylar, ada turları ve Tay masajıyla Güneydoğu Asya\'nın en popüler plaj destinasyonu.',
    highlights: ['Patong Beach', 'Phi Phi Adaları', 'Big Buddha', 'Phang Nga Körfezi', 'Old Phuket Town'],
    bestTimeToVisit: 'Kasım - Nisan',
    timezone: 'UTC+7',
    currency: 'Baht (THB)',
    language: 'Tayca',
    population: '400 bin',
    image: 'https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=1200&h=600&fit=crop',
  },
  'chiangmai': {
    slug: 'chiangmai',
    name: 'Chiang Mai',
    nameEn: 'Chiang Mai',
    country: 'Tayland',
    countryCode: 'TH',
    airportCodes: ['CNX'],
    description: 'Chiang Mai, Kuzey Tayland\'ın kültür başkenti ve dijital göçebe cenneti. Yüzlerce tapınak, fil barınakları, trekking rotaları ve uygun fiyatlarla uzaktan çalışanların favorisi.',
    highlights: ['Eski Şehir Tapınakları', 'Doi Suthep', 'Fil Barınakları', 'Gece Pazarı', 'Yemek Kursları'],
    bestTimeToVisit: 'Kasım - Şubat',
    timezone: 'UTC+7',
    currency: 'Baht (THB)',
    language: 'Tayca',
    population: '130 bin',
    image: 'https://images.unsplash.com/photo-1598935898639-81586f7d2129?w=1200&h=600&fit=crop',
  },
  'kualalumpur': {
    slug: 'kualalumpur',
    name: 'Kuala Lumpur',
    nameEn: 'Kuala Lumpur',
    country: 'Malezya',
    countryCode: 'MY',
    airportCodes: ['KUL'],
    description: 'Kuala Lumpur, Malezya\'nın başkenti ve Güneydoğu Asya\'nın yükselen yıldızı. Petronas İkiz Kuleleri, çok kültürlü yemek sahnesi ve uygun fiyatlarla bölgenin en dinamik şehri.',
    highlights: ['Petronas Kuleleri', 'Batu Mağaraları', 'Merdeka Meydanı', 'Chinatown', 'KLCC Parkı'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+8',
    currency: 'Malezya Ringgiti (MYR)',
    language: 'Malayca, İngilizce',
    population: '1.8 milyon',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1200&h=600&fit=crop',
  },
  'hongkong': {
    slug: 'hongkong',
    name: 'Hong Kong',
    nameEn: 'Hong Kong',
    country: 'Hong Kong',
    countryCode: 'HK',
    airportCodes: ['HKG'],
    description: 'Hong Kong, Doğu ve Batı\'nın buluştuğu global finans merkezi. Victoria Peak manzaraları, dim sum kültürü, alışveriş cennetleri ve gökdelen ormanıyla benzersiz bir şehir.',
    highlights: ['Victoria Peak', 'Lantau Adası', 'Temple Street', 'Star Ferry', 'Kowloon'],
    bestTimeToVisit: 'Ekim - Aralık',
    timezone: 'UTC+8',
    currency: 'Hong Kong Doları (HKD)',
    language: 'Kantonca, İngilizce',
    population: '7.5 milyon',
    image: 'https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=1200&h=600&fit=crop',
  },
  'taipei': {
    slug: 'taipei',
    name: 'Taipei',
    nameEn: 'Taipei',
    country: 'Tayvan',
    countryCode: 'TW',
    airportCodes: ['TPE'],
    description: 'Taipei, Tayvan\'ın başkenti ve Asya\'nın gizli hazinesi. Taipei 101, gece pazarları, kaplıcalar ve dünya standartlarında gastronomi ile keşfedilmeyi bekleyen modern şehir.',
    highlights: ['Taipei 101', 'Shilin Gece Pazarı', 'Longshan Tapınağı', 'Beitou Kaplıcaları', 'Jiufen'],
    bestTimeToVisit: 'Ekim - Aralık, Mart - Mayıs',
    timezone: 'UTC+8',
    currency: 'Yeni Tayvan Doları (TWD)',
    language: 'Mandarin',
    population: '2.6 milyon',
    image: 'https://images.unsplash.com/photo-1470004914212-05527e49370b?w=1200&h=600&fit=crop',
  },
  'hanoi': {
    slug: 'hanoi',
    name: 'Hanoi',
    nameEn: 'Hanoi',
    country: 'Vietnam',
    countryCode: 'VN',
    airportCodes: ['HAN'],
    description: 'Hanoi, Vietnam\'ın başkenti ve Güneydoğu Asya\'nın en karizmatik şehri. Eski mahalle sokaklarında tren geçişi, pho kültürü ve Fransız koloni mirasıyla benzersiz atmosfer.',
    highlights: ['Eski Mahalle', 'Ho Chi Minh Mozolesi', 'Hoan Kiem Gölü', 'Temple of Literature', 'Halong Körfezi (günübirlik)'],
    bestTimeToVisit: 'Ekim - Aralık, Mart - Nisan',
    timezone: 'UTC+7',
    currency: 'Vietnam Dongu (VND)',
    language: 'Vietnamca',
    population: '8 milyon',
    image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=1200&h=600&fit=crop',
  },
  'hochiminh': {
    slug: 'hochiminh',
    name: 'Ho Chi Minh',
    nameEn: 'Ho Chi Minh City',
    country: 'Vietnam',
    countryCode: 'VN',
    airportCodes: ['SGN'],
    description: 'Ho Chi Minh (Saigon), Vietnam\'ın en büyük şehri ve ekonomik merkezi. Motosiklet kaosı, Fransız koloni binaları, Vietnam Savaşı tarihi ve canlı gece hayatıyla güneyin kalbi.',
    highlights: ['Ben Thanh Pazarı', 'Savaş Kalıntıları Müzesi', 'Notre Dame Katedrali', 'Cu Chi Tünelleri', 'Mekong Deltası'],
    bestTimeToVisit: 'Aralık - Nisan',
    timezone: 'UTC+7',
    currency: 'Vietnam Dongu (VND)',
    language: 'Vietnamca',
    population: '9 milyon',
    image: 'https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=1200&h=600&fit=crop',
  },
  'manila': {
    slug: 'manila',
    name: 'Manila',
    nameEn: 'Manila',
    country: 'Filipinler',
    countryCode: 'PH',
    airportCodes: ['MNL'],
    description: 'Manila, Filipinler\'in başkenti ve Güneydoğu Asya\'nın en kalabalık metropollerinden biri. İspanyol koloni tarihi Intramuros, canlı alışveriş merkezleri ve Filipin mutfağıyla tanınır.',
    highlights: ['Intramuros', 'Rizal Parkı', 'SM Mall of Asia', 'Binondo Chinatown', 'San Agustin Kilisesi'],
    bestTimeToVisit: 'Kasım - Mayıs',
    timezone: 'UTC+8',
    currency: 'Filipin Pesosu (PHP)',
    language: 'Filipince, İngilizce',
    population: '1.8 milyon',
    image: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=1200&h=600&fit=crop',
  },
  'mumbai': {
    slug: 'mumbai',
    name: 'Mumbai',
    nameEn: 'Mumbai',
    country: 'Hindistan',
    countryCode: 'IN',
    airportCodes: ['BOM'],
    description: 'Mumbai, Hindistan\'ın finans başkenti ve Bollywood\'un evi. Gateway of India, Victoria döneminden kalma mimari ve kontrastlarla dolu yaşamıyla Güney Asya\'nın en büyük metropolü.',
    highlights: ['Gateway of India', 'Marine Drive', 'Elephanta Mağaraları', 'Dharavi', 'Chhatrapati Shivaji Terminus'],
    bestTimeToVisit: 'Kasım - Şubat',
    timezone: 'UTC+5:30',
    currency: 'Hint Rupisi (INR)',
    language: 'Hintçe, Marathi, İngilizce',
    population: '20 milyon',
    image: 'https://images.unsplash.com/photo-1566552881560-0be862a7c445?w=1200&h=600&fit=crop',
  },
  'delhi': {
    slug: 'delhi',
    name: 'Delhi',
    nameEn: 'Delhi',
    country: 'Hindistan',
    countryCode: 'IN',
    airportCodes: ['DEL'],
    description: 'Delhi, Hindistan\'ın başkenti ve tarihsel başkentlerin üzerine kurulu megapol. Kırmızı Kale, Qutub Minar, eski ve yeni Delhi kontrastı ve zengin Mughal mirasıyla Güney Asya\'nın kalbi.',
    highlights: ['Kırmızı Kale', 'Qutub Minar', 'India Gate', 'Humayun Türbesi', 'Chandni Chowk'],
    bestTimeToVisit: 'Ekim - Mart',
    timezone: 'UTC+5:30',
    currency: 'Hint Rupisi (INR)',
    language: 'Hintçe, İngilizce',
    population: '32 milyon',
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=1200&h=600&fit=crop',
  },
  'katmandu': {
    slug: 'katmandu',
    name: 'Katmandu',
    nameEn: 'Kathmandu',
    country: 'Nepal',
    countryCode: 'NP',
    airportCodes: ['KTM'],
    description: 'Katmandu, Nepal\'in başkenti ve Himalaya\'nın kapısı. Boudhanath stupası, Durbar Meydanı, trekking turlarının başlangıç noktası ve manevi atmosferiyle benzersiz destinasyon.',
    highlights: ['Boudhanath', 'Swayambhunath', 'Durbar Meydanı', 'Pashupatinath', 'Thamel'],
    bestTimeToVisit: 'Ekim - Aralık, Mart - Nisan',
    timezone: 'UTC+5:45',
    currency: 'Nepal Rupisi (NPR)',
    language: 'Nepalce',
    population: '1.4 milyon',
    image: 'https://images.unsplash.com/photo-1558799401-1dcba79834c2?w=1200&h=600&fit=crop',
  },

  // === ORTADOĞU & AFRİKA - EKSİK ŞEHİRLER ===
  'abudabi': {
    slug: 'abudabi',
    name: 'Abu Dabi',
    nameEn: 'Abu Dhabi',
    country: 'BAE',
    countryCode: 'AE',
    airportCodes: ['AUH'],
    description: 'Abu Dabi, BAE\'nin başkenti ve petrol zenginliğinin simgesi. Sheikh Zayed Camii, Louvre Abu Dhabi ve lüks adalarla Dubai\'ye sofistike alternatif.',
    highlights: ['Sheikh Zayed Camii', 'Louvre Abu Dhabi', 'Emirates Palace', 'Yas Island', 'Corniche'],
    bestTimeToVisit: 'Kasım - Mart',
    timezone: 'UTC+4',
    currency: 'Dirham (AED)',
    language: 'Arapça, İngilizce',
    population: '1.5 milyon',
    image: 'https://images.unsplash.com/photo-1512632578888-169bbbc64f33?w=1200&h=600&fit=crop',
  },
  'doha': {
    slug: 'doha',
    name: 'Doha',
    nameEn: 'Doha',
    country: 'Katar',
    countryCode: 'QA',
    airportCodes: ['DOH'],
    description: 'Doha, Katar\'ın başkenti ve 2022 Dünya Kupası ev sahibi. Müze çöl adasına dönüşen şehir, İslam Sanatları Müzesi ve modern mimarisiyle yükselen Körfez yıldızı.',
    highlights: ['İslam Sanatları Müzesi', 'The Pearl', 'Souq Waqif', 'Katara Kültür Köyü', 'Corniche'],
    bestTimeToVisit: 'Kasım - Nisan',
    timezone: 'UTC+3',
    currency: 'Katar Riyali (QAR)',
    language: 'Arapça, İngilizce',
    population: '2 milyon',
    image: 'https://images.unsplash.com/photo-1559564484-e48b3e040ff4?w=1200&h=600&fit=crop',
  },
  'kahire': {
    slug: 'kahire',
    name: 'Kahire',
    nameEn: 'Cairo',
    country: 'Mısır',
    countryCode: 'EG',
    airportCodes: ['CAI'],
    description: 'Kahire, Mısır\'ın başkenti ve dünyanın en eski medeniyetinin kalbi. Giza Piramitleri, Sfenks, Mısır Müzesi ve Nil Nehri ile insanlık tarihinin en önemli destinasyonu.',
    highlights: ['Giza Piramitleri', 'Sfenks', 'Mısır Müzesi', 'Han el-Halili', 'Nil Nehri'],
    bestTimeToVisit: 'Ekim - Nisan',
    timezone: 'UTC+2',
    currency: 'Mısır Lirası (EGP)',
    language: 'Arapça',
    population: '21 milyon',
    image: 'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=1200&h=600&fit=crop',
  },
  'capetown': {
    slug: 'capetown',
    name: 'Cape Town',
    nameEn: 'Cape Town',
    country: 'Güney Afrika',
    countryCode: 'ZA',
    airportCodes: ['CPT'],
    description: 'Cape Town, Güney Afrika\'nın en güzel şehri ve Afrika\'nın güneybatı ucu. Table Mountain, penguen kolonileri, şarap bağları ve Ümit Burnu ile doğa ve kültürün buluştuğu nokta.',
    highlights: ['Table Mountain', 'Robben Adası', 'Cape of Good Hope', 'V&A Waterfront', 'Boulders Penguenleri'],
    bestTimeToVisit: 'Kasım - Mart',
    timezone: 'UTC+2',
    currency: 'Güney Afrika Randı (ZAR)',
    language: 'İngilizce, Afrikanca',
    population: '4.7 milyon',
    image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=1200&h=600&fit=crop',
  },
  'mauritius': {
    slug: 'mauritius',
    name: 'Mauritius',
    nameEn: 'Mauritius',
    country: 'Mauritius',
    countryCode: 'MU',
    airportCodes: ['MRU'],
    description: 'Mauritius, Hint Okyanusu\'nun cennet adası. Beyaz kumlu plajlar, lüks resortlar, çok kültürlü miras ve sualtı şelalesi illüzyonuyla romantik kaçış destinasyonu.',
    highlights: ['Grand Baie', 'Le Morne', 'Chamarel', 'Port Louis', 'Pamplemousses Botanik Bahçesi'],
    bestTimeToVisit: 'Mayıs - Aralık',
    timezone: 'UTC+4',
    currency: 'Mauritius Rupisi (MUR)',
    language: 'İngilizce, Fransızca, Kreol',
    population: '1.3 milyon',
    image: 'https://images.unsplash.com/photo-1589979481223-deb893043163?w=1200&h=600&fit=crop',
  },
  'maldivler': {
    slug: 'maldivler',
    name: 'Maldivler',
    nameEn: 'Maldives',
    country: 'Maldivler',
    countryCode: 'MV',
    airportCodes: ['MLE'],
    description: 'Maldivler, Hint Okyanusu\'ndaki 1.000 mercan adasından oluşan cennet takımadaları. Suüstü bungalovlar, turkuaz lagünler ve snorkeling ile dünyanın en lüks balayı destinasyonu.',
    highlights: ['Su Üstü Bungalovlar', 'Dalış ve Snorkeling', 'Özel Adalar', 'Biyolüminesans Plajlar', 'Whale Shark Dalışı'],
    bestTimeToVisit: 'Kasım - Nisan',
    timezone: 'UTC+5',
    currency: 'Maldiv Rufiyası (MVR)',
    language: 'Dhivehi, İngilizce',
    population: '560 bin',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&h=600&fit=crop',
  },
  'seyseller': {
    slug: 'seyseller',
    name: 'Seyşeller',
    nameEn: 'Seychelles',
    country: 'Seyşeller',
    countryCode: 'SC',
    airportCodes: ['SEZ'],
    description: 'Seyşeller, Hint Okyanusu\'nun granit cennet adaları. Anse Source d\'Argent gibi dünyanın en güzel plajları, benzersiz flora fauna ve lüks resortlarla tropikal kaçış.',
    highlights: ['Anse Source d\'Argent', 'Praslin Adası', 'Vallée de Mai', 'Victoria', 'Mahé Adası'],
    bestTimeToVisit: 'Nisan - Mayıs, Ekim - Kasım',
    timezone: 'UTC+4',
    currency: 'Seyşel Rupisi (SCR)',
    language: 'İngilizce, Fransızca, Kreol',
    population: '100 bin',
    image: 'https://images.unsplash.com/photo-1589979481223-deb893043163?w=1200&h=600&fit=crop',
  },

  // === AMERİKA - EKSİK ŞEHİRLER ===
  'losangeles': {
    slug: 'losangeles',
    name: 'Los Angeles',
    nameEn: 'Los Angeles',
    country: 'ABD',
    countryCode: 'US',
    airportCodes: ['LAX'],
    description: 'Los Angeles, Hollywood\'un evi ve Amerikan rüyasının başkenti. Yıldızlar Geçidi, Santa Monica Pier, Beverly Hills ve Kaliforniya güneşiyle eğlence endüstrisinin kalbi.',
    highlights: ['Hollywood', 'Santa Monica', 'Beverly Hills', 'Universal Studios', 'Getty Center'],
    bestTimeToVisit: 'Mart - Mayıs, Eylül - Kasım',
    timezone: 'UTC-8',
    currency: 'Amerikan Doları (USD)',
    language: 'İngilizce',
    population: '4 milyon',
    image: 'https://images.unsplash.com/photo-1534190760961-74e8c1c5c3da?w=1200&h=600&fit=crop',
  },
  'miami': {
    slug: 'miami',
    name: 'Miami',
    nameEn: 'Miami',
    country: 'ABD',
    countryCode: 'US',
    airportCodes: ['MIA'],
    description: 'Miami, Florida\'nın tropikal metropolü ve Latin Amerika\'nın ABD kapısı. South Beach, Art Deco mimarisi, küba sandviçleri ve gece hayatıyla Karayip ruhunu yaşatan şehir.',
    highlights: ['South Beach', 'Art Deco District', 'Wynwood', 'Little Havana', 'Everglades'],
    bestTimeToVisit: 'Aralık - Mayıs',
    timezone: 'UTC-5',
    currency: 'Amerikan Doları (USD)',
    language: 'İngilizce, İspanyolca',
    population: '470 bin',
    image: 'https://images.unsplash.com/photo-1506966953602-c20cc11f75e3?w=1200&h=600&fit=crop',
  },
  'lasvegas': {
    slug: 'lasvegas',
    name: 'Las Vegas',
    nameEn: 'Las Vegas',
    country: 'ABD',
    countryCode: 'US',
    airportCodes: ['LAS'],
    description: 'Las Vegas, çölün ortasındaki eğlence başkenti. The Strip üzerindeki devasa oteller, kumarhaneler, dünya standartlarındaki şovlar ve Grand Canyon turlarıyla "günah şehri".',
    highlights: ['The Strip', 'Bellagio Çeşmeleri', 'Grand Canyon', 'Fremont Street', 'Cirque du Soleil'],
    bestTimeToVisit: 'Mart - Mayıs, Eylül - Kasım',
    timezone: 'UTC-8',
    currency: 'Amerikan Doları (USD)',
    language: 'İngilizce',
    population: '660 bin',
    image: 'https://images.unsplash.com/photo-1605833556294-ea5c7a74f57d?w=1200&h=600&fit=crop',
  },
  'sanfrancisco': {
    slug: 'sanfrancisco',
    name: 'San Francisco',
    nameEn: 'San Francisco',
    country: 'ABD',
    countryCode: 'US',
    airportCodes: ['SFO'],
    description: 'San Francisco, Silikon Vadisi\'nin kapısı ve Kaliforniya\'nın kültür başkenti. Golden Gate Köprüsü, Alcatraz, tarihi tramvaylar ve tepeler arasında özgür ruhlu şehir.',
    highlights: ['Golden Gate Köprüsü', 'Alcatraz', 'Fisherman\'s Wharf', 'Chinatown', 'Cable Cars'],
    bestTimeToVisit: 'Eylül - Kasım',
    timezone: 'UTC-8',
    currency: 'Amerikan Doları (USD)',
    language: 'İngilizce',
    population: '870 bin',
    image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=1200&h=600&fit=crop',
  },
  'chicago': {
    slug: 'chicago',
    name: 'Chicago',
    nameEn: 'Chicago',
    country: 'ABD',
    countryCode: 'US',
    airportCodes: ['ORD'],
    description: 'Chicago, ABD\'nin mimari başkenti ve "Rüzgarlı Şehir". Gökdelenler, deep-dish pizza, blues müziği ve Michigan Gölü kıyısında kültür ve gastronomi cenneti.',
    highlights: ['Millennium Park', 'Willis Tower', 'Navy Pier', 'Art Institute', 'Magnificent Mile'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC-6',
    currency: 'Amerikan Doları (USD)',
    language: 'İngilizce',
    population: '2.7 milyon',
    image: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1200&h=600&fit=crop',
  },
  'toronto': {
    slug: 'toronto',
    name: 'Toronto',
    nameEn: 'Toronto',
    country: 'Kanada',
    countryCode: 'CA',
    airportCodes: ['YYZ'],
    description: 'Toronto, Kanada\'nın en büyük şehri ve çokkültürlülüğün başkenti. CN Tower, Niagara Şelalesi günübirlik turları ve 200\'den fazla etnik kökenli nüfusuyla kozmopolit metropol.',
    highlights: ['CN Tower', 'Niagara Şelalesi', 'Royal Ontario Museum', 'Distillery District', 'St. Lawrence Market'],
    bestTimeToVisit: 'Mayıs - Ekim',
    timezone: 'UTC-5',
    currency: 'Kanada Doları (CAD)',
    language: 'İngilizce, Fransızca',
    population: '2.9 milyon',
    image: 'https://images.unsplash.com/photo-1517090504586-fde19ea6066f?w=1200&h=600&fit=crop',
  },
  'vancouver': {
    slug: 'vancouver',
    name: 'Vancouver',
    nameEn: 'Vancouver',
    country: 'Kanada',
    countryCode: 'CA',
    airportCodes: ['YVR'],
    description: 'Vancouver, Kanada\'nın Pasifik kapısı ve dünyanın en yaşanabilir şehirlerinden biri. Dağlar ve okyanus arasında, Stanley Park, kayak ve doğa maceralarıyla çevrili.',
    highlights: ['Stanley Park', 'Granville Island', 'Capilano Köprüsü', 'Gastown', 'Whistler (günübirlik)'],
    bestTimeToVisit: 'Mayıs - Ekim',
    timezone: 'UTC-8',
    currency: 'Kanada Doları (CAD)',
    language: 'İngilizce',
    population: '680 bin',
    image: 'https://images.unsplash.com/photo-1559511260-66a68ebd8d5e?w=1200&h=600&fit=crop',
  },
  'cancun': {
    slug: 'cancun',
    name: 'Cancun',
    nameEn: 'Cancun',
    country: 'Meksika',
    countryCode: 'MX',
    airportCodes: ['CUN'],
    description: 'Cancun, Meksika\'nın Karayip cenneti ve Maya medeniyetinin kapısı. Turkuaz suları, all-inclusive resortlar, Chichen Itza turları ve canlı gece hayatıyla tatil cenneti.',
    highlights: ['Plajlar', 'Chichen Itza', 'Xcaret', 'Isla Mujeres', 'Cenote\'ler'],
    bestTimeToVisit: 'Aralık - Nisan',
    timezone: 'UTC-5',
    currency: 'Meksika Pesosu (MXN)',
    language: 'İspanyolca',
    population: '890 bin',
    image: 'https://images.unsplash.com/photo-1552074284-5e88ef1aef18?w=1200&h=600&fit=crop',
  },
  'rio': {
    slug: 'rio',
    name: 'Rio de Janeiro',
    nameEn: 'Rio de Janeiro',
    country: 'Brezilya',
    countryCode: 'BR',
    airportCodes: ['GIG'],
    description: 'Rio de Janeiro, "Harika Şehir" ve samba\'nın kalbi. Kurtarıcı İsa heykeli, Copacabana plajı, karnaval coşkusu ve Sugarloaf Dağı ile Latin Amerika\'nın en ikonik şehri.',
    highlights: ['Kurtarıcı İsa', 'Copacabana', 'Sugarloaf Dağı', 'Ipanema', 'Rio Karnavalı'],
    bestTimeToVisit: 'Aralık - Mart',
    timezone: 'UTC-3',
    currency: 'Brezilya Reali (BRL)',
    language: 'Portekizce',
    population: '6.7 milyon',
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1200&h=600&fit=crop',
  },
  'buenosaires': {
    slug: 'buenosaires',
    name: 'Buenos Aires',
    nameEn: 'Buenos Aires',
    country: 'Arjantin',
    countryCode: 'AR',
    airportCodes: ['EZE'],
    description: 'Buenos Aires, "Güney Amerika\'nın Paris\'i" ve tango\'nun doğum yeri. Avrupa mimarisi, biftek kültürü, canlı mahalleler ve Latin tutkusuyla kıtanın en kozmopolit şehri.',
    highlights: ['La Boca', 'San Telmo', 'Recoleta', 'Teatro Colón', 'Puerto Madero'],
    bestTimeToVisit: 'Mart - Mayıs, Eylül - Kasım',
    timezone: 'UTC-3',
    currency: 'Arjantin Pesosu (ARS)',
    language: 'İspanyolca',
    population: '3 milyon',
    image: 'https://images.unsplash.com/photo-1589909202802-8f4aadce1849?w=1200&h=600&fit=crop',
  },

  // === OKYANUSYA - EKSİK ŞEHİRLER ===
  'sydney': {
    slug: 'sydney',
    name: 'Sydney',
    nameEn: 'Sydney',
    country: 'Avustralya',
    countryCode: 'AU',
    airportCodes: ['SYD'],
    description: 'Sydney, Avustralya\'nın en büyük şehri ve ikonik limanın sahibi. Opera Binası, Harbour Bridge, Bondi Beach ve kozmopolit yaşam tarzıyla güney yarımkürenin en çekici metropolü.',
    highlights: ['Sydney Opera House', 'Harbour Bridge', 'Bondi Beach', 'Darling Harbour', 'The Rocks'],
    bestTimeToVisit: 'Eylül - Kasım, Mart - Mayıs',
    timezone: 'UTC+10',
    currency: 'Avustralya Doları (AUD)',
    language: 'İngilizce',
    population: '5.3 milyon',
    image: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=1200&h=600&fit=crop',
  },
  'melbourne': {
    slug: 'melbourne',
    name: 'Melbourne',
    nameEn: 'Melbourne',
    country: 'Avustralya',
    countryCode: 'AU',
    airportCodes: ['MEL'],
    description: 'Melbourne, Avustralya\'nın kültür başkenti ve dünyanın en yaşanabilir şehri. Sokak sanatı, kahve kültürü, spor etkinlikleri ve çok kültürlü gastronomiyle sanat ve yaşam tarzının merkezi.',
    highlights: ['Federation Square', 'Laneways & Street Art', 'Great Ocean Road', 'Melbourne Cricket Ground', 'Queen Victoria Market'],
    bestTimeToVisit: 'Eylül - Kasım, Mart - Mayıs',
    timezone: 'UTC+10',
    currency: 'Avustralya Doları (AUD)',
    language: 'İngilizce',
    population: '5 milyon',
    image: 'https://images.unsplash.com/photo-1514395462725-fb4566210144?w=1200&h=600&fit=crop',
  },
  'auckland': {
    slug: 'auckland',
    name: 'Auckland',
    nameEn: 'Auckland',
    country: 'Yeni Zelanda',
    countryCode: 'NZ',
    airportCodes: ['AKL'],
    description: 'Auckland, Yeni Zelanda\'nın en büyük şehri ve "Yelkenlilerin Şehri". İki liman arasında, volkanik tepeler, Maori kültürü ve macera sporlarıyla Pasifik\'in kapısı.',
    highlights: ['Sky Tower', 'Waiheke Adası', 'Viaduct Harbour', 'Auckland Müzesi', 'Rangitoto Adası'],
    bestTimeToVisit: 'Aralık - Şubat',
    timezone: 'UTC+12',
    currency: 'Yeni Zelanda Doları (NZD)',
    language: 'İngilizce, Maori',
    population: '1.7 milyon',
    image: 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=1200&h=600&fit=crop',
  },

  // === ORTA ASYA & KAFKASLAR - EKSİK ŞEHİRLER ===
  'almati': {
    slug: 'almati',
    name: 'Almatı',
    nameEn: 'Almaty',
    country: 'Kazakistan',
    countryCode: 'KZ',
    airportCodes: ['ALA'],
    description: 'Almatı, Kazakistan\'ın en büyük şehri ve eski başkent. Tian Shan dağları arka planında, yeşil bulvarlar, kayak merkezleri ve Sovyet mirası mimarisiye Orta Asya\'nın vitrini.',
    highlights: ['Medeu Buz Pisti', 'Shymbulak Kayak', 'Zenkov Katedrali', 'Kok Tobe', 'Charyn Kanyonu'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+6',
    currency: 'Kazak Tengesi (KZT)',
    language: 'Kazakça, Rusça',
    population: '2 milyon',
    image: 'https://images.unsplash.com/photo-1580737422753-90aab3ed0e27?w=1200&h=600&fit=crop',
  },
  'taskent': {
    slug: 'taskent',
    name: 'Taşkent',
    nameEn: 'Tashkent',
    country: 'Özbekistan',
    countryCode: 'UZ',
    airportCodes: ['TAS'],
    description: 'Taşkent, Özbekistan\'ın başkenti ve Orta Asya\'nın en büyük şehri. İpek Yolu mirası, Sovyet döneminden kalma geniş bulvarlar ve modern kalkınmayla Orta Asya\'nın kapısı.',
    highlights: ['Khast Imam Kompleksi', 'Chorsu Pazarı', 'Taşkent Metrosu', 'Bağımsızlık Meydanı', 'Minor Camii'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+5',
    currency: 'Özbek Som (UZS)',
    language: 'Özbekçe, Rusça',
    population: '2.5 milyon',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1200&h=600&fit=crop',
  },
  'semerkand': {
    slug: 'semerkand',
    name: 'Semerkand',
    nameEn: 'Samarkand',
    country: 'Özbekistan',
    countryCode: 'UZ',
    airportCodes: ['SKD'],
    description: 'Semerkand, İpek Yolu\'nun incisi ve Timur İmparatorluğu\'nun başkenti. Registan Meydanı, turkuaz kubbeler ve 2500 yıllık tarihiyle Orta Asya\'nın en büyülü şehri.',
    highlights: ['Registan Meydanı', 'Gur-e Amir', 'Bibi-Khanym Camii', 'Shah-i-Zinda', 'Afrosiab Müzesi'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+5',
    currency: 'Özbek Som (UZS)',
    language: 'Özbekçe',
    population: '540 bin',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1200&h=600&fit=crop',
  },
  'erivan': {
    slug: 'erivan',
    name: 'Erivan',
    nameEn: 'Yerevan',
    country: 'Ermenistan',
    countryCode: 'AM',
    airportCodes: ['EVN'],
    description: 'Erivan, dünyanın en eski sürekli yerleşim yerlerinden biri ve Ermenistan\'ın başkenti. Ağrı Dağı manzaraları, antik manastırlar ve pembe tüf taşından yapılmış "Pembe Şehir".',
    highlights: ['Republic Meydanı', 'Cascade', 'Ağrı Dağı Manzarası', 'Matenadaran', 'Garni Tapınağı'],
    bestTimeToVisit: 'Mayıs - Haziran, Eylül - Ekim',
    timezone: 'UTC+4',
    currency: 'Ermeni Dramı (AMD)',
    language: 'Ermenice',
    population: '1.1 milyon',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=1200&h=600&fit=crop',
  },
};
