// City data for hub pages
export interface CityEvent {
  name: string;
  nameEn: string;
  date: string; // "27 Nisan" or "Ağustos 7-13" for ranges
  description: string;
}

export interface CityInfo {
  slug: string;
  name: string;
  nameEn: string;
  country: string;
  countryCode: string;
  airportCodes: string[];
  description: string;
  highlights: string[];
  bestTimeToVisit: string;
  timezone: string;
  currency: string;
  language: string;
  population: string;
  image: string;
  events?: CityEvent[];
}

export const cityData: Record<string, CityInfo> = {
  // === TÜRKİYE ===
  'istanbul': {
    slug: 'istanbul',
    name: 'İstanbul',
    nameEn: 'Istanbul',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['IST', 'SAW'],
    description: 'İstanbul, Avrupa ve Asya\'yı birleştiren, 2500 yıllık tarihe sahip dünyanın en büyüleyici metropolü. Ayasofya, Sultanahmet Camii, Topkapı Sarayı ve Kapalıçarşı ile tarihin canlı bir müzesi.',
    highlights: ['Ayasofya', 'Sultanahmet Camii', 'Topkapı Sarayı', 'Kapalıçarşı', 'Boğaz Turu', 'Galata Kulesi'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Kasım',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '16 milyon',
    image: 'https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=1200&h=600&fit=crop',
    events: [
      { name: 'İstanbul Lale Festivali', nameEn: 'Istanbul Tulip Festival', date: 'Nisan', description: 'Milyonlarca lale ile renklenen şehir parkları.' },
      { name: 'İstanbul Film Festivali', nameEn: 'Istanbul Film Festival', date: 'Nisan', description: 'Türkiye\'nin en prestijli film festivali.' },
      { name: 'İstanbul Müzik Festivali', nameEn: 'Istanbul Music Festival', date: 'Haziran', description: 'Klasik müzik ve opera festivali.' },
      { name: 'İstanbul Bienali', nameEn: 'Istanbul Biennial', date: 'Eylül-Kasım (tek yıllar)', description: 'Uluslararası çağdaş sanat bienali.' },
    ],
  },
  'antalya': {
    slug: 'antalya',
    name: 'Antalya',
    nameEn: 'Antalya',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['AYT'],
    description: 'Antalya, Türkiye\'nin turizm başkenti ve Akdeniz\'in incisi. Turkuaz suları, antik kalıntıları, lüks otelleri ve yılın 300 günü güneşli havası ile tatil cenneti.',
    highlights: ['Kaleiçi', 'Düden Şelalesi', 'Konyaaltı Plajı', 'Aspendos', 'Side', 'Perge'],
    bestTimeToVisit: 'Mayıs - Ekim',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '2.5 milyon',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&h=600&fit=crop',
    events: [
      { name: 'Antalya Film Festivali', nameEn: 'Antalya Film Festival', date: 'Ekim', description: 'Türkiye\'nin en eski film festivali.' },
      { name: 'Aspendos Opera ve Bale Festivali', nameEn: 'Aspendos Festival', date: 'Haziran-Temmuz', description: 'Antik tiyatroda dünya standartlarında performanslar.' },
      { name: 'Antalya Maratonu', nameEn: 'Antalya Marathon', date: 'Mart', description: 'Deniz manzaralı maraton parkuru.' },
    ],
  },
  'izmir': {
    slug: 'izmir',
    name: 'İzmir',
    nameEn: 'Izmir',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['ADB'],
    description: 'İzmir, Ege\'nin incisi ve Türkiye\'nin üçüncü büyük şehri. Kordon boyu, antik Efes kalıntıları, Çeşme\'nin turkuaz plajları ve enfes Ege mutfağı ile yaşanabilirlik şampiyonu.',
    highlights: ['Kordon', 'Saat Kulesi', 'Efes Antik Kenti', 'Alaçatı', 'Çeşme', 'Şirince'],
    bestTimeToVisit: 'Mayıs - Ekim',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '4.4 milyon',
    image: 'https://images.unsplash.com/photo-1598887142487-3c854d51eabb?w=1200&h=600&fit=crop',
    events: [
      { name: 'İzmir Fuarı', nameEn: 'Izmir International Fair', date: 'Eylül', description: 'Türkiye\'nin en eski uluslararası fuarı.' },
      { name: 'Alaçatı Ot Festivali', nameEn: 'Alaçatı Herb Festival', date: 'Nisan', description: 'Ege\'nin otları ve yerel lezzetleri.' },
      { name: 'Efes Festivali', nameEn: 'Ephesus Festival', date: 'Mayıs', description: 'Antik tiyatroda konserler ve etkinlikler.' },
    ],
  },
  'bodrum': {
    slug: 'bodrum',
    name: 'Bodrum',
    nameEn: 'Bodrum',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['BJV'],
    description: 'Bodrum, Türkiye\'nin Saint-Tropez\'i ve Ege\'nin en glamuröz tatil beldesi. Beyaz evleri, lüks yatları, dünyaca ünlü gece hayatı ve antik Mausoleum kalıntıları.',
    highlights: ['Bodrum Kalesi', 'Gümbet', 'Yalıkavak Marina', 'Türkbükü', 'Bitez', 'Antik Tiyatro'],
    bestTimeToVisit: 'Haziran - Eylül',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '180 bin',
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=1200&h=600&fit=crop',
    events: [
      { name: 'Bodrum Bale Festivali', nameEn: 'Bodrum Ballet Festival', date: 'Ağustos', description: 'Bodrum Kalesi\'nde bale performansları.' },
      { name: 'Bodrum Caz Festivali', nameEn: 'Bodrum Jazz Festival', date: 'Temmuz', description: 'Uluslararası caz yıldızları.' },
      { name: 'Gümüşlük Müzik Festivali', nameEn: 'Gümüşlük Music Festival', date: 'Temmuz-Ağustos', description: 'Klasik müzik konserleri.' },
    ],
  },
  'kapadokya': {
    slug: 'kapadokya',
    name: 'Kapadokya',
    nameEn: 'Cappadocia',
    country: 'Türkiye',
    countryCode: 'TR',
    airportCodes: ['ASR', 'NAV'],
    description: 'Kapadokya, peri bacaları, yeraltı şehirleri ve sıcak hava balonlarıyla dünyanın en sürreal destinasyonu. Göreme Açık Hava Müzesi ve kaya otellerle eşsiz bir deneyim.',
    highlights: ['Göreme', 'Peri Bacaları', 'Yeraltı Şehirleri', 'Balon Turu', 'Uçhisar Kalesi', 'Aşk Vadisi'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Kasım',
    timezone: 'UTC+3',
    currency: 'Türk Lirası (TRY)',
    language: 'Türkçe',
    population: '100 bin',
    image: 'https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?w=1200&h=600&fit=crop',
    events: [
      { name: 'Kapadokya Balon Festivali', nameEn: 'Cappadocia Balloon Festival', date: 'Temmuz', description: 'Yüzlerce balonla renklenen gökyüzü.' },
      { name: 'Ürgüp Bağ Bozumu', nameEn: 'Ürgüp Grape Harvest', date: 'Eylül', description: 'Şarap festivali ve hasat kutlamaları.' },
    ],
  },
  
  // === ALMANYA ===
  'berlin': {
    slug: 'berlin',
    name: 'Berlin',
    nameEn: 'Berlin',
    country: 'Almanya',
    countryCode: 'DE',
    airportCodes: ['BER', 'TXL'],
    description: 'Berlin, Almanya\'nın başkenti ve en büyük şehri. Zengin tarihi, canlı sanat sahnesi ve kozmopolit atmosferiyle ünlüdür. Brandenburg Kapısı, Berlin Duvarı kalıntıları ve dünya standartlarındaki müzeleriyle turistleri cezbeder.',
    highlights: ['Brandenburg Kapısı', 'Berlin Duvarı', 'Museum Island', 'Reichstag', 'Checkpoint Charlie'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'Almanca',
    population: '3.7 milyon',
    image: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=1200&h=600&fit=crop',
    events: [
      { name: 'Berlin Film Festivali', nameEn: 'Berlinale', date: 'Şubat 13-23', description: 'Dünyanın en prestijli film festivallerinden biri.' },
      { name: 'Karneval der Kulturen', nameEn: 'Carnival of Cultures', date: 'Haziran 7-10', description: 'Çok kültürlü sokak festivali ve geçit töreni.' },
      { name: 'Berlin Maratonu', nameEn: 'Berlin Marathon', date: 'Eylül 28', description: 'Dünyanın en hızlı maraton parkurlarından biri.' },
      { name: 'Festival of Lights', nameEn: 'Festival of Lights', date: 'Ekim 4-13', description: 'Ünlü yapıların ışıkla aydınlatıldığı festival.' },
    ],
  },
  'munih': {
    slug: 'munih',
    name: 'Münih',
    nameEn: 'Munich',
    country: 'Almanya',
    countryCode: 'DE',
    airportCodes: ['MUC'],
    description: 'Münih, Bavyera\'nın başkenti ve Almanya\'nın üçüncü büyük şehri. Alman kültürünün kalbi, dünyaca ünlü bira bahçeleri ve Oktoberfest\'in doğum yeridir.',
    highlights: ['Marienplatz', 'Neuschwanstein Şatosu', 'Englischer Garten', 'BMW Welt', 'Nymphenburg Sarayı'],
    bestTimeToVisit: 'Mayıs - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'Almanca',
    population: '1.5 milyon',
    image: 'https://images.unsplash.com/photo-1595867818082-083862f3d630?w=1200&h=600&fit=crop',
    events: [
      { name: 'Oktoberfest', nameEn: 'Oktoberfest', date: 'Eylül 20 - Ekim 5', description: 'Dünyanın en büyük bira festivali, 6 milyon ziyaretçi.' },
      { name: 'Münih Noel Pazarı', nameEn: 'Munich Christmas Market', date: 'Kasım 25 - Aralık 24', description: 'Almanya\'nın en güzel Noel pazarlarından biri.' },
      { name: 'Starkbierfest', nameEn: 'Strong Beer Festival', date: 'Mart 14-30', description: 'Güçlü Lent biralarının festivali.' },
    ],
  },
  'frankfurt': {
    slug: 'frankfurt',
    name: 'Frankfurt',
    nameEn: 'Frankfurt',
    country: 'Almanya',
    countryCode: 'DE',
    airportCodes: ['FRA'],
    description: 'Frankfurt, Avrupa\'nın finans merkezi ve Almanya\'nın en önemli ulaşım hub\'ı. Modern gökdelenler, tarihi Römer Meydanı ve canlı sanat sahnesine ev sahipliği yapar.',
    highlights: ['Römerberg', 'Main Tower', 'Palmengarten', 'Städel Museum', 'Main Nehri'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'Almanca',
    population: '750 bin',
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?w=1200&h=600&fit=crop',
    events: [
      { name: 'Frankfurt Kitap Fuarı', nameEn: 'Frankfurt Book Fair', date: 'Ekim 16-20', description: 'Dünyanın en büyük kitap fuarı.' },
      { name: 'Museumsuferfest', nameEn: 'Museum Embankment Festival', date: 'Ağustos 22-24', description: 'Main nehri boyunca müzeler ve sanat festivali.' },
    ],
  },

  // === FRANSA ===
  'paris': {
    slug: 'paris',
    name: 'Paris',
    nameEn: 'Paris',
    country: 'Fransa',
    countryCode: 'FR',
    airportCodes: ['CDG', 'ORY'],
    description: 'Paris, "Işıklar Şehri" olarak bilinen Fransa\'nın başkenti. Eyfel Kulesi, Louvre Müzesi, Notre-Dame Katedrali ve romantik atmosferiyle dünyanın en çok ziyaret edilen şehirlerinden biridir.',
    highlights: ['Eyfel Kulesi', 'Louvre Müzesi', 'Notre-Dame', 'Champs-Élysées', 'Montmartre'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'Fransızca',
    population: '2.1 milyon',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&h=600&fit=crop',
    events: [
      { name: 'Bastille Günü', nameEn: 'Bastille Day', date: '14 Temmuz', description: 'Fransa Ulusal Günü, Champs-Élysées\'de askeri geçit töreni ve havai fişek.' },
      { name: 'Paris Fashion Week', nameEn: 'Paris Fashion Week', date: 'Şubat/Mart ve Eylül/Ekim', description: 'Dünyanın en prestijli moda haftalarından biri.' },
      { name: 'Nuit Blanche', nameEn: 'White Night', date: 'Ekim 5', description: 'Tüm gece açık kalan müzeler ve sanat etkinlikleri.' },
      { name: 'Roland Garros', nameEn: 'French Open', date: 'Mayıs 25 - Haziran 8', description: 'Grand Slam tenis turnuvası.' },
    ],
  },

  // === İNGİLTERE ===
  'londra': {
    slug: 'londra',
    name: 'Londra',
    nameEn: 'London',
    country: 'İngiltere',
    countryCode: 'GB',
    airportCodes: ['LHR', 'LGW', 'STN'],
    description: 'Londra, İngiltere\'nin başkenti ve Avrupa\'nın en büyük metropollerinden biri. Big Ben, Buckingham Sarayı, Tower Bridge ve British Museum ile tarihi dokuyu modernlikle harmanlayan benzersiz bir şehir.',
    highlights: ['Big Ben', 'Tower of London', 'British Museum', 'Buckingham Palace', 'London Eye'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+0',
    currency: 'Pound Sterling (GBP)',
    language: 'İngilizce',
    population: '9 milyon',
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&h=600&fit=crop',
    events: [
      { name: 'Wimbledon', nameEn: 'Wimbledon', date: 'Haziran 30 - Temmuz 13', description: 'Dünyanın en prestijli tenis turnuvası.' },
      { name: 'Notting Hill Karnavalı', nameEn: 'Notting Hill Carnival', date: 'Ağustos 24-25', description: 'Avrupa\'nın en büyük sokak festivali.' },
      { name: 'Guy Fawkes Night', nameEn: 'Bonfire Night', date: '5 Kasım', description: 'Havai fişek ve şenlik ateşi geceleri.' },
      { name: 'Trooping the Colour', nameEn: 'Trooping the Colour', date: 'Haziran 14', description: 'Kraliçenin resmi doğum günü töreni.' },
    ],
  },

  // === HOLLANDA ===
  'amsterdam': {
    slug: 'amsterdam',
    name: 'Amsterdam',
    nameEn: 'Amsterdam',
    country: 'Hollanda',
    countryCode: 'NL',
    airportCodes: ['AMS'],
    description: 'Amsterdam, Hollanda\'nın başkenti. Pitoresk kanalları, tarihi evleri, dünyaca ünlü müzeleri ve bisiklet dostu altyapısıyla tanınır. Van Gogh Müzesi ve Anne Frank Evi en popüler turistik noktalarıdır.',
    highlights: ['Van Gogh Museum', 'Anne Frank House', 'Rijksmuseum', 'Kanallar', 'Vondelpark'],
    bestTimeToVisit: 'Nisan - Mayıs, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'Hollandaca',
    population: '870 bin',
    image: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&h=600&fit=crop',
    events: [
      { name: 'Kral Günü', nameEn: 'King\'s Day', date: '27 Nisan', description: 'Hollanda\'nın en büyük festivali, tüm şehir turuncuya bürünür.' },
      { name: 'Amsterdam Light Festival', nameEn: 'Amsterdam Light Festival', date: 'Aralık - Ocak', description: 'Kanallar boyunca ışık heykelleri ve enstalasyonlar.' },
      { name: 'Keukenhof Lale Bahçeleri', nameEn: 'Keukenhof', date: 'Mart 20 - Mayıs 11', description: 'Dünyanın en büyük lale bahçesi (Amsterdam yakını).' },
      { name: 'Pride Amsterdam', nameEn: 'Pride Amsterdam', date: 'Ağustos 2-10', description: 'Kanal geçit töreni ile ünlü pride festivali.' },
    ],
  },

  // === İSPANYA ===
  'barcelona': {
    slug: 'barcelona',
    name: 'Barselona',
    nameEn: 'Barcelona',
    country: 'İspanya',
    countryCode: 'ES',
    airportCodes: ['BCN'],
    description: 'Barselona, İspanya\'nın Katalonya bölgesinin başkenti. Gaudi\'nin mimari şaheserleri, Akdeniz sahilleri ve canlı gece hayatıyla ünlüdür. La Sagrada Familia dünyanın en etkileyici yapılarından biridir.',
    highlights: ['La Sagrada Familia', 'Park Güell', 'La Rambla', 'Camp Nou', 'Gotik Mahalle'],
    bestTimeToVisit: 'Mayıs - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'İspanyolca, Katalanca',
    population: '1.6 milyon',
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=1200&h=600&fit=crop',
    events: [
      { name: 'La Mercè', nameEn: 'La Mercè Festival', date: 'Eylül 20-24', description: 'Barselona\'nın en büyük festivali, insan kuleleri ve ateş gösterileri.' },
      { name: 'Sant Jordi Günü', nameEn: 'Saint George\'s Day', date: '23 Nisan', description: 'Kitap ve gül hediye etme geleneği, Katalan Valentine\'ı.' },
      { name: 'Primavera Sound', nameEn: 'Primavera Sound', date: 'Haziran 4-8', description: 'Avrupa\'nın en büyük müzik festivallerinden biri.' },
      { name: 'Sónar', nameEn: 'Sónar', date: 'Haziran 12-14', description: 'Elektronik müzik ve ileri teknoloji festivali.' },
    ],
  },
  'madrid': {
    slug: 'madrid',
    name: 'Madrid',
    nameEn: 'Madrid',
    country: 'İspanya',
    countryCode: 'ES',
    airportCodes: ['MAD'],
    description: 'Madrid, İspanya\'nın başkenti ve en büyük şehri. Prado Müzesi, Kraliyet Sarayı, canlı tapas kültürü ve gece hayatıyla ünlüdür. İspanyol sanatının ve kültürünün kalbi.',
    highlights: ['Prado Müzesi', 'Kraliyet Sarayı', 'Retiro Parkı', 'Gran Vía', 'Plaza Mayor'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'İspanyolca',
    population: '3.3 milyon',
    image: 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1200&h=600&fit=crop',
    events: [
      { name: 'San Isidro', nameEn: 'San Isidro Festival', date: 'Mayıs 15', description: 'Madrid\'in koruyucu azizi festivali, boğa güreşi ve geleneksel danslar.' },
      { name: 'Mad Cool', nameEn: 'Mad Cool Festival', date: 'Temmuz 9-12', description: 'Büyük uluslararası müzik festivali.' },
      { name: 'Üç Kral Günü Geçit Töreni', nameEn: 'Three Kings Parade', date: '5 Ocak', description: 'Geleneksel Epifani geçit töreni.' },
    ],
  },

  // === İTALYA ===
  'roma': {
    slug: 'roma',
    name: 'Roma',
    nameEn: 'Rome',
    country: 'İtalya',
    countryCode: 'IT',
    airportCodes: ['FCO'],
    description: 'Roma, "Ebedi Şehir" olarak bilinen İtalya\'nın başkenti. Antik Roma İmparatorluğu\'nun kalıntıları, Vatikan ve dünya mutfağının öncüsü İtalyan mutfağıyla tarih ve lezzetin buluştuğu eşsiz bir destinasyon.',
    highlights: ['Kolezyum', 'Vatikan', 'Trevi Çeşmesi', 'Pantheon', 'Roma Forumu'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'İtalyanca',
    population: '2.8 milyon',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&h=600&fit=crop',
    events: [
      { name: 'Paskalya (Vatikan)', nameEn: 'Easter at Vatican', date: 'Nisan 20-21', description: 'Papa\'nın Paskalya ayini, St. Peter Meydanı\'nda.' },
      { name: 'Natale di Roma', nameEn: 'Birthday of Rome', date: '21 Nisan', description: 'Roma\'nın kuruluş yıldönümü kutlamaları.' },
      { name: 'Estate Romana', nameEn: 'Roman Summer', date: 'Haziran - Eylül', description: 'Yaz boyu açık hava konser ve sinema etkinlikleri.' },
    ],
  },
  'milano': {
    slug: 'milano',
    name: 'Milano',
    nameEn: 'Milan',
    country: 'İtalya',
    countryCode: 'IT',
    airportCodes: ['MXP', 'LIN'],
    description: 'Milano, İtalya\'nın moda ve tasarım başkenti. Duomo, La Scala Operası ve dünya modasının merkezi olarak tanınır. Alışveriş tutkunları için cennet.',
    highlights: ['Duomo di Milano', 'La Scala', 'Galleria Vittorio Emanuele II', 'Son Akşam Yemeği', 'Sforza Kalesi'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'İtalyanca',
    population: '1.4 milyon',
    image: 'https://images.unsplash.com/photo-1520440229-6469a149ac59?w=1200&h=600&fit=crop',
    events: [
      { name: 'Milan Fashion Week', nameEn: 'Milan Fashion Week', date: 'Şubat ve Eylül', description: 'Dünyanın dört büyük moda haftasından biri.' },
      { name: 'Salone del Mobile', nameEn: 'Milan Design Week', date: 'Nisan 8-13', description: 'Dünyanın en büyük mobilya ve tasarım fuarı.' },
      { name: 'Milano Film Festivali', nameEn: 'Milano Film Festival', date: 'Eylül', description: 'Bağımsız sinema festivali.' },
    ],
  },
  'venedik': {
    slug: 'venedik',
    name: 'Venedik',
    nameEn: 'Venice',
    country: 'İtalya',
    countryCode: 'IT',
    airportCodes: ['VCE'],
    description: 'Venedik, su üzerine kurulu eşsiz bir şehir. 118 ada, 400\'den fazla köprü ve romantik gondol turlarıyla dünyanın en romantik destinasyonlarından biri.',
    highlights: ['San Marco Meydanı', 'Rialto Köprüsü', 'Doge Sarayı', 'Murano Adası', 'Grand Canal'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'İtalyanca',
    population: '260 bin',
    image: 'https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?w=1200&h=600&fit=crop',
    events: [
      { name: 'Venedik Karnavalı', nameEn: 'Venice Carnival', date: 'Şubat 14 - Mart 4', description: 'Dünyanın en ünlü karnavallarından biri, maskeli balolar.' },
      { name: 'Venedik Film Festivali', nameEn: 'Venice Film Festival', date: 'Ağustos 27 - Eylül 6', description: 'Dünyanın en eski film festivali.' },
      { name: 'Regata Storica', nameEn: 'Historical Regatta', date: 'Eylül 7', description: 'Grand Canal\'da tarihi kostümlü kürek yarışı.' },
      { name: 'Venedik Bienali', nameEn: 'Venice Biennale', date: 'Mayıs - Kasım', description: 'Dünyanın en prestijli sanat bienali (tek yıllarda sanat, çift yıllarda mimari).' },
    ],
  },
  'floransa': {
    slug: 'floransa',
    name: 'Floransa',
    nameEn: 'Florence',
    country: 'İtalya',
    countryCode: 'IT',
    airportCodes: ['FLR'],
    description: 'Floransa, Rönesans\'ın doğum yeri. Uffizi Galerisi, Michelangelo\'nun David heykeli ve muhteşem katedraliyle sanat tarihinin kalbi.',
    highlights: ['Uffizi Galerisi', 'Duomo', 'Ponte Vecchio', 'Accademia Galerisi', 'Piazzale Michelangelo'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'İtalyanca',
    population: '380 bin',
    image: 'https://images.unsplash.com/photo-1543429258-c5ca3d4d5d4b?w=1200&h=600&fit=crop',
    events: [
      { name: 'Calcio Storico', nameEn: 'Historic Football', date: 'Haziran 24', description: 'Tarihi Floransa futbolu, Rönesans dönemi kıyafetleriyle.' },
      { name: 'Scoppio del Carro', nameEn: 'Explosion of the Cart', date: 'Paskalya Pazar', description: 'Geleneksel Paskalya havai fişek töreni.' },
      { name: 'Festa della Rificolona', nameEn: 'Festival of Paper Lanterns', date: '7 Eylül', description: 'Kağıt fener festivali.' },
    ],
  },

  // === PORTEKİZ ===
  'lizbon': {
    slug: 'lizbon',
    name: 'Lizbon',
    nameEn: 'Lisbon',
    country: 'Portekiz',
    countryCode: 'PT',
    airportCodes: ['LIS'],
    description: 'Lizbon, Portekiz\'in başkenti ve en büyük şehri. Yedi tepe üzerine kurulu şehir, nostaljik tramvayları, fado müziği ve muhteşem Atlantik manzaralarıyla büyüler.',
    highlights: ['Belém Kulesi', 'Jerónimos Manastırı', 'Alfama', 'Sintra', 'Tram 28'],
    bestTimeToVisit: 'Mart - Mayıs, Eylül - Ekim',
    timezone: 'UTC+0',
    currency: 'Euro (EUR)',
    language: 'Portekizce',
    population: '550 bin',
    image: 'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?w=1200&h=600&fit=crop',
    events: [
      { name: 'Santos Populares', nameEn: 'Popular Saints Festival', date: 'Haziran 1-30', description: 'Özellikle 12-13 Haziran\'da Santo António festivali, sokak partileri.' },
      { name: 'Rock in Rio Lisboa', nameEn: 'Rock in Rio Lisbon', date: 'Haziran', description: 'Büyük müzik festivali (çift yıllarda).' },
      { name: 'Festas de Lisboa', nameEn: 'Lisbon Festivities', date: 'Haziran', description: 'Sardunya ve şarap ile kutlanan sokak festivalleri.' },
    ],
  },
  'porto': {
    slug: 'porto',
    name: 'Porto',
    nameEn: 'Porto',
    country: 'Portekiz',
    countryCode: 'PT',
    airportCodes: ['OPO'],
    description: 'Porto, Portekiz\'in ikinci büyük şehri ve Port şarabının doğum yeri. Renkli evleri, tarihi şarap mahzenleri ve Douro Nehri manzaralarıyla büyüleyici.',
    highlights: ['Ribeira', 'Livraria Lello', 'Dom Luís I Köprüsü', 'Clérigos Kulesi', 'Port Şarabı Mahzenleri'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+0',
    currency: 'Euro (EUR)',
    language: 'Portekizce',
    population: '240 bin',
    image: 'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?w=1200&h=600&fit=crop',
    events: [
      { name: 'São João', nameEn: 'St. John\'s Festival', date: '23-24 Haziran', description: 'Porto\'nun en büyük festivali, havai fişek ve plastik çekiçlerle kutlama.' },
      { name: 'Fantasporto', nameEn: 'Fantasporto', date: 'Şubat-Mart', description: 'Uluslararası fantezi film festivali.' },
      { name: 'NOS Primavera Sound Porto', nameEn: 'Primavera Sound Porto', date: 'Haziran 5-7', description: 'Büyük müzik festivali.' },
    ],
  },

  // === YUNANİSTAN ===
  'atina': {
    slug: 'atina',
    name: 'Atina',
    nameEn: 'Athens',
    country: 'Yunanistan',
    countryCode: 'GR',
    airportCodes: ['ATH'],
    description: 'Atina, Avrupa medeniyetinin beşiği ve Yunanistan\'ın başkenti. Akropolis, Parthenon ve 3000 yıllık tarihiyle antik dünyanın en önemli şehri.',
    highlights: ['Akropolis', 'Parthenon', 'Plaka', 'Ulusal Arkeoloji Müzesi', 'Monastiraki'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+2',
    currency: 'Euro (EUR)',
    language: 'Yunanca',
    population: '3.1 milyon',
    image: 'https://images.unsplash.com/photo-1555993539-1732b0258235?w=1200&h=600&fit=crop',
    events: [
      { name: 'Atina Epidaurus Festivali', nameEn: 'Athens Epidaurus Festival', date: 'Haziran - Ağustos', description: 'Antik tiyatrolarda drama ve müzik performansları.' },
      { name: 'Yunan Paskalyası', nameEn: 'Greek Easter', date: 'Nisan (Ortodoks)', description: 'Yunanistan\'ın en önemli dini bayramı.' },
      { name: 'Atina Maratonu', nameEn: 'Athens Marathon', date: 'Kasım 9', description: 'Orijinal maraton rotası üzerinde tarihi koşu.' },
    ],
  },

  // === ORTA AVRUPA ===
  'prag': {
    slug: 'prag',
    name: 'Prag',
    nameEn: 'Prague',
    country: 'Çekya',
    countryCode: 'CZ',
    airportCodes: ['PRG'],
    description: 'Prag, "Yüz Kuleli Şehir" olarak bilinen Çekya\'nın başkenti. Ortaçağ mimarisi, gotik katedraller ve romantik atmosferiyle Avrupa\'nın en güzel şehirlerinden biri.',
    highlights: ['Charles Bridge', 'Prague Castle', 'Old Town Square', 'Astronomical Clock', 'St. Vitus Cathedral'],
    bestTimeToVisit: 'Nisan - Mayıs, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Koruna (CZK)',
    language: 'Çekçe',
    population: '1.3 milyon',
    image: 'https://images.unsplash.com/photo-1541849546-216549ae216d?w=1200&h=600&fit=crop',
    events: [
      { name: 'Prague Spring', nameEn: 'Prague Spring', date: 'Mayıs 12 - Haziran 3', description: 'Uluslararası klasik müzik festivali.' },
      { name: 'Signal Festival', nameEn: 'Signal Festival', date: 'Ekim 16-19', description: 'Işık ve video mapping festivali.' },
      { name: 'Prag Noel Pazarları', nameEn: 'Prague Christmas Markets', date: 'Kasım 30 - Ocak 6', description: 'Avrupa\'nın en güzel Noel pazarlarından biri.' },
    ],
  },
  'viyana': {
    slug: 'viyana',
    name: 'Viyana',
    nameEn: 'Vienna',
    country: 'Avusturya',
    countryCode: 'AT',
    airportCodes: ['VIE'],
    description: 'Viyana, Avusturya\'nın başkenti ve kültür başkenti. Mozart, Beethoven gibi büyük bestecilerin yaşadığı şehir, operaları, sarayları ve kahve kültürüyle tanınır.',
    highlights: ['Schönbrunn Palace', 'St. Stephen\'s Cathedral', 'Belvedere Palace', 'Vienna State Opera', 'Naschmarkt'],
    bestTimeToVisit: 'Nisan - Ekim',
    timezone: 'UTC+1',
    currency: 'Euro (EUR)',
    language: 'Almanca',
    population: '1.9 milyon',
    image: 'https://images.unsplash.com/photo-1516550893923-42d28e5677af?w=1200&h=600&fit=crop',
    events: [
      { name: 'Viyana Opera Balosu', nameEn: 'Vienna Opera Ball', date: 'Şubat 27', description: 'Dünyanın en prestijli balolarından biri.' },
      { name: 'Donauinselfest', nameEn: 'Danube Island Festival', date: 'Haziran 20-22', description: 'Avrupa\'nın en büyük açık hava müzik festivali, ücretsiz.' },
      { name: 'Viyana Film Festivali', nameEn: 'Viennale', date: 'Ekim 17-29', description: 'Avusturya\'nın en büyük film festivali.' },
      { name: 'Viyana Noel Pazarları', nameEn: 'Vienna Christmas Markets', date: 'Kasım 15 - Aralık 26', description: 'Belediye binası önündeki büyülü Noel pazarı.' },
    ],
  },
  'budapeste': {
    slug: 'budapeste',
    name: 'Budapeşte',
    nameEn: 'Budapest',
    country: 'Macaristan',
    countryCode: 'HU',
    airportCodes: ['BUD'],
    description: 'Budapeşte, "Tuna\'nın İncisi" olarak bilinen Macaristan\'ın başkenti. Termal kaplıcaları, görkemli mimarisi ve canlı gece hayatıyla ünlüdür.',
    highlights: ['Parlamento Binası', 'Balıkçı Kalesi', 'Széchenyi Kaplıcası', 'Budapeşte Kalesi', 'Zincir Köprü'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+1',
    currency: 'Forint (HUF)',
    language: 'Macarca',
    population: '1.7 milyon',
    image: 'https://images.unsplash.com/photo-1551867633-194f125bddfa?w=1200&h=600&fit=crop',
    events: [
      { name: 'Sziget Festivali', nameEn: 'Sziget Festival', date: 'Ağustos 6-11', description: 'Avrupa\'nın en büyük müzik festivallerinden biri, 400.000+ ziyaretçi.' },
      { name: 'Budapeşte Şarap Festivali', nameEn: 'Budapest Wine Festival', date: 'Eylül 11-14', description: 'Buda Kalesi\'nde düzenlenen şarap festivali.' },
      { name: 'Formula 1 Macaristan GP', nameEn: 'Hungarian Grand Prix', date: 'Temmuz 27', description: 'Hungaroring\'de düzenlenen F1 yarışı.' },
      { name: 'Budapeşte Noel Fuarı', nameEn: 'Budapest Christmas Fair', date: 'Kasım 15 - Aralık 31', description: 'Vörösmarty Meydanı\'ndaki geleneksel Noel pazarı.' },
    ],
  },

  // === İSKANDİNAVYA ===
  'kopenhag': {
    slug: 'kopenhag',
    name: 'Kopenhag',
    nameEn: 'Copenhagen',
    country: 'Danimarka',
    countryCode: 'DK',
    airportCodes: ['CPH'],
    description: 'Kopenhag, Danimarka\'nın başkenti ve "hygge" kavramının doğum yeri. Renkli Nyhavn limanı, Tivoli Bahçeleri ve bisiklet dostu altyapısıyla tanınır.',
    highlights: ['Nyhavn', 'Tivoli Bahçeleri', 'Küçük Deniz Kızı', 'Christiania', 'Rosenborg Şatosu'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+1',
    currency: 'Danimarka Kronu (DKK)',
    language: 'Danimarka\'ca',
    population: '800 bin',
    image: 'https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=1200&h=600&fit=crop',
    events: [
      { name: 'Copenhagen Jazz Festival', nameEn: 'Copenhagen Jazz Festival', date: 'Temmuz 4-13', description: 'Avrupa\'nın en büyük caz festivallerinden biri.' },
      { name: 'Distortion', nameEn: 'Distortion', date: 'Mayıs 28 - Haziran 1', description: 'Sokak müziği ve parti festivali.' },
      { name: 'Tivoli Noel', nameEn: 'Tivoli Christmas', date: 'Kasım 15 - Aralık 31', description: 'Büyülü Tivoli Bahçeleri Noel teması.' },
    ],
  },
  'stockholm': {
    slug: 'stockholm',
    name: 'Stockholm',
    nameEn: 'Stockholm',
    country: 'İsveç',
    countryCode: 'SE',
    airportCodes: ['ARN'],
    description: 'Stockholm, 14 ada üzerine kurulu İsveç\'in başkenti. "Kuzey\'in Venedik\'i" olarak anılan şehir, Nobel Ödülleri ve muhteşem mimarisiyle ünlüdür.',
    highlights: ['Gamla Stan', 'Vasa Müzesi', 'Skansen', 'ABBA Müzesi', 'Kraliyet Sarayı'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+1',
    currency: 'İsveç Kronu (SEK)',
    language: 'İsveççe',
    population: '980 bin',
    image: 'https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=1200&h=600&fit=crop',
    events: [
      { name: 'Midsommar', nameEn: 'Midsummer', date: 'Haziran 20-21', description: 'İsveç\'in en önemli geleneksel festivali, yaz gündönümü kutlaması.' },
      { name: 'Nobel Ödül Töreni', nameEn: 'Nobel Prize Ceremony', date: '10 Aralık', description: 'Nobel Ödülleri\'nin verildiği prestijli tören.' },
      { name: 'Stockholm Kültür Festivali', nameEn: 'Stockholm Culture Festival', date: 'Ağustos 13-18', description: 'Şehir genelinde ücretsiz kültür etkinlikleri.' },
    ],
  },

  // === ORTADOĞU ===
  'dubai': {
    slug: 'dubai',
    name: 'Dubai',
    nameEn: 'Dubai',
    country: 'BAE',
    countryCode: 'AE',
    airportCodes: ['DXB'],
    description: 'Dubai, Birleşik Arap Emirlikleri\'nin en büyük şehri. Burj Khalifa, lüks alışveriş merkezleri ve çöl safarilarıyla modern mimarinin ve geleneksel Arap kültürünün harmanlandığı benzersiz bir destinasyon.',
    highlights: ['Burj Khalifa', 'Dubai Mall', 'Palm Jumeirah', 'Burj Al Arab', 'Desert Safari'],
    bestTimeToVisit: 'Kasım - Mart',
    timezone: 'UTC+4',
    currency: 'Dirham (AED)',
    language: 'Arapça, İngilizce',
    population: '3.4 milyon',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&h=600&fit=crop',
    events: [
      { name: 'Dubai Shopping Festival', nameEn: 'Dubai Shopping Festival', date: 'Aralık 15 - Ocak 29', description: 'Büyük indirimler ve etkinliklerle dolu alışveriş festivali.' },
      { name: 'Dubai Expo', nameEn: 'Dubai Expo', date: 'Yıl boyunca', description: 'Expo City Dubai\'de sürekli etkinlikler.' },
      { name: 'Dubai Food Festival', nameEn: 'Dubai Food Festival', date: 'Şubat 21 - Mart 9', description: 'Gastronomi festivali, sokak lezzetleri.' },
      { name: 'Yeni Yıl Havai Fişekleri', nameEn: 'New Year Fireworks', date: '31 Aralık', description: 'Burj Khalifa\'da muhteşem havai fişek gösterisi.' },
    ],
  },
  'amman': {
    slug: 'amman',
    name: 'Amman',
    nameEn: 'Amman',
    country: 'Ürdün',
    countryCode: 'JO',
    airportCodes: ['AMM'],
    description: 'Amman, Ürdün\'ün başkenti ve modern ile antik dünyayı bir arada yaşatan şehir. Petra ve Ölü Deniz\'e açılan kapı, Roma kalıntıları ve sıcak Ortadoğu misafirperverliğiyle tanınır.',
    highlights: ['Citadel', 'Roma Tiyatrosu', 'Rainbow Street', 'Petra (günübirlik)', 'Ölü Deniz (günübirlik)'],
    bestTimeToVisit: 'Mart - Mayıs, Eylül - Kasım',
    timezone: 'UTC+2',
    currency: 'Ürdün Dinarı (JOD)',
    language: 'Arapça',
    population: '4.5 milyon',
    image: 'https://images.unsplash.com/photo-1580834341580-8c17a3a630ca?w=1200&h=600&fit=crop',
    events: [
      { name: 'Jerash Festivali', nameEn: 'Jerash Festival', date: 'Temmuz', description: 'Antik Roma şehrinde kültür ve sanat festivali.' },
      { name: 'Amman Design Week', nameEn: 'Amman Design Week', date: 'Ekim', description: 'Ortadoğu\'nun önemli tasarım etkinliği.' },
    ],
  },
  'tiflis': {
    slug: 'tiflis',
    name: 'Tiflis',
    nameEn: 'Tbilisi',
    country: 'Gürcistan',
    countryCode: 'GE',
    airportCodes: ['TBS'],
    description: 'Tiflis, Gürcistan\'ın başkenti ve Kafkasya\'nın en renkli şehri. Kükürt hamamları, eski şehir sokakları, muhteşem mutfağı ve şarap kültürüyle benzersiz bir destinasyon.',
    highlights: ['Old Town', 'Narikala Kalesi', 'Abanotubani Hamamları', 'Rustaveli Bulvarı', 'Dry Bridge Pazarı'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+4',
    currency: 'Gürcü Larisi (GEL)',
    language: 'Gürcüce',
    population: '1.2 milyon',
    image: 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1200&h=600&fit=crop',
    events: [
      { name: 'Tbilisoba', nameEn: 'Tbilisoba', date: 'Ekim', description: 'Tiflis\'in yıllık şehir festivali, geleneksel müzik ve yemekler.' },
      { name: 'Art Gene Festival', nameEn: 'Art Gene Festival', date: 'Temmuz', description: 'Açık havada etnik müzik festivali.' },
      { name: 'New Wine Festival', nameEn: 'New Wine Festival', date: 'Mayıs', description: 'Gürcü şarapları festivali.' },
    ],
  },
  'baku': {
    slug: 'baku',
    name: 'Bakü',
    nameEn: 'Baku',
    country: 'Azerbaycan',
    countryCode: 'AZ',
    airportCodes: ['GYD'],
    description: 'Bakü, Azerbaycan\'ın başkenti ve Hazar Denizi\'nin incisi. UNESCO Dünya Mirası olan eski şehir, modern Flame Towers ve zengin petrol mirası ile Doğu ve Batı\'nın buluştuğu nokta.',
    highlights: ['Eski Şehir (İçərişəhər)', 'Flame Towers', 'Haydar Aliyev Merkezi', 'Kız Kalesi', 'Seaside Boulevard'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Ekim',
    timezone: 'UTC+4',
    currency: 'Azerbaycan Manatı (AZN)',
    language: 'Azerice',
    population: '2.3 milyon',
    image: 'https://images.unsplash.com/photo-1568430462989-44163eb1752f?w=1200&h=600&fit=crop',
    events: [
      { name: 'Formula 1 Azerbaycan GP', nameEn: 'Azerbaijan Grand Prix', date: 'Nisan', description: 'Bakü sokak pistinde düzenlenen F1 yarışı.' },
      { name: 'Novruz Bayramı', nameEn: 'Novruz', date: '20-21 Mart', description: 'Farsça yeni yıl, bahar bayramı kutlamaları.' },
      { name: 'Caspian Oil & Gas', nameEn: 'Caspian Oil & Gas', date: 'Haziran', description: 'Bölgenin en büyük enerji fuarı.' },
    ],
  },

  // === ASYA ===
  'tokyo': {
    slug: 'tokyo',
    name: 'Tokyo',
    nameEn: 'Tokyo',
    country: 'Japonya',
    countryCode: 'JP',
    airportCodes: ['NRT', 'HND'],
    description: 'Tokyo, Japonya\'nın başkenti ve dünyanın en büyük metropollerinden biri. Geleneksel tapınaklar, fütüristik teknoloji, anime kültürü ve eşsiz mutfağıyla Doğu ile Batı\'nın buluştuğu benzersiz bir şehir.',
    highlights: ['Sensoji Temple', 'Shibuya Crossing', 'Tokyo Tower', 'Akihabara', 'Meiji Shrine'],
    bestTimeToVisit: 'Mart - Mayıs, Eylül - Kasım',
    timezone: 'UTC+9',
    currency: 'Yen (JPY)',
    language: 'Japonca',
    population: '14 milyon',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&h=600&fit=crop',
    events: [
      { name: 'Sakura Sezonu', nameEn: 'Cherry Blossom Season', date: 'Mart sonu - Nisan başı', description: 'Kiraz çiçeği izleme (hanami) festivali.' },
      { name: 'Sanja Matsuri', nameEn: 'Sanja Matsuri', date: 'Mayıs 16-18', description: 'Asakusa\'da Tokyo\'nun en büyük festivali.' },
      { name: 'Tokyo Game Show', nameEn: 'Tokyo Game Show', date: 'Eylül 25-28', description: 'Dünyanın en büyük video oyun fuarlarından biri.' },
      { name: 'Comiket', nameEn: 'Comiket', date: 'Ağustos ve Aralık', description: 'Dünyanın en büyük manga/anime etkinliği.' },
    ],
  },
  'bangkok': {
    slug: 'bangkok',
    name: 'Bangkok',
    nameEn: 'Bangkok',
    country: 'Tayland',
    countryCode: 'TH',
    airportCodes: ['BKK', 'DMK'],
    description: 'Bangkok, Tayland\'ın başkenti. Altın tapınaklar, canlı sokak yemek kültürü, yüzen pazarlar ve eğlence hayatıyla Güneydoğu Asya\'nın en popüler destinasyonlarından biri.',
    highlights: ['Grand Palace', 'Wat Pho', 'Chatuchak Market', 'Khao San Road', 'Floating Markets'],
    bestTimeToVisit: 'Kasım - Şubat',
    timezone: 'UTC+7',
    currency: 'Baht (THB)',
    language: 'Tayca',
    population: '10 milyon',
    image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579c4e?w=1200&h=600&fit=crop',
    events: [
      { name: 'Songkran Su Festivali', nameEn: 'Songkran', date: '13-15 Nisan', description: 'Tay yeni yılı, dünyanın en büyük su savaşı.' },
      { name: 'Loy Krathong', nameEn: 'Loy Krathong', date: 'Kasım (Dolunay)', description: 'Suya mum ve çiçek bırakılan fener festivali.' },
      { name: 'Bangkok International Film Festival', nameEn: 'Bangkok Film Festival', date: 'Aralık', description: 'Güneydoğu Asya\'nın önemli film festivali.' },
    ],
  },
  'singapur': {
    slug: 'singapur',
    name: 'Singapur',
    nameEn: 'Singapore',
    country: 'Singapur',
    countryCode: 'SG',
    airportCodes: ['SIN'],
    description: 'Singapur, Güneydoğu Asya\'nın modern şehir devleti. Marina Bay Sands, Gardens by the Bay ve dünya standartlarındaki altyapısıyla geleceğin şehri olarak anılır.',
    highlights: ['Marina Bay Sands', 'Gardens by the Bay', 'Sentosa Island', 'Orchard Road', 'Chinatown'],
    bestTimeToVisit: 'Şubat - Nisan',
    timezone: 'UTC+8',
    currency: 'Singapur Doları (SGD)',
    language: 'İngilizce, Mandarin, Malayca, Tamil',
    population: '5.7 milyon',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200&h=600&fit=crop',
    events: [
      { name: 'Singapur F1 Gece Yarışı', nameEn: 'Singapore Grand Prix', date: 'Eylül 19-21', description: 'Dünyanın ilk gece F1 yarışı.' },
      { name: 'Çin Yeni Yılı', nameEn: 'Chinese New Year', date: 'Ocak/Şubat', description: 'Chinatown\'da muhteşem kutlamalar.' },
      { name: 'National Day', nameEn: 'National Day', date: '9 Ağustos', description: 'Singapur bağımsızlık günü, havai fişek ve geçit töreni.' },
      { name: 'Deepavali', nameEn: 'Deepavali', date: 'Ekim/Kasım', description: 'Işık festivali, Little India\'da kutlamalar.' },
    ],
  },
  'bali': {
    slug: 'bali',
    name: 'Bali',
    nameEn: 'Bali',
    country: 'Endonezya',
    countryCode: 'ID',
    airportCodes: ['DPS'],
    description: 'Bali, "Tanrıların Adası" olarak bilinen Endonezya\'nın en popüler turistik destinasyonu. Tropikal plajlar, pirinç terasları, tapınaklar ve yoga retreat\'leriyle ruhsal bir kaçış noktası.',
    highlights: ['Ubud Pirinç Terasları', 'Tanah Lot Tapınağı', 'Uluwatu', 'Seminyak', 'Tirta Empul'],
    bestTimeToVisit: 'Nisan - Ekim',
    timezone: 'UTC+8',
    currency: 'Endonezya Rupisi (IDR)',
    language: 'Endonezce, Balice',
    population: '4.3 milyon',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&h=600&fit=crop',
    events: [
      { name: 'Nyepi (Sessizlik Günü)', nameEn: 'Nyepi', date: 'Mart (Bali takvimi)', description: 'Bali yeni yılı, tüm ada 24 saat sessiz kalır.' },
      { name: 'Galungan ve Kuningan', nameEn: 'Galungan', date: 'Her 210 günde bir', description: 'Bali\'nin en önemli Hindu festivali.' },
      { name: 'Bali Spirit Festival', nameEn: 'Bali Spirit Festival', date: 'Mayıs', description: 'Yoga, dans ve müzik festivali.' },
      { name: 'Ubud Writers & Readers Festival', nameEn: 'Ubud Writers Festival', date: 'Ekim', description: 'Güneydoğu Asya\'nın önde gelen edebiyat festivali.' },
    ],
  },
  'seul': {
    slug: 'seul',
    name: 'Seul',
    nameEn: 'Seoul',
    country: 'Güney Kore',
    countryCode: 'KR',
    airportCodes: ['ICN', 'GMP'],
    description: 'Seul, Güney Kore\'nin başkenti ve K-pop kültürünün kalbi. Geleneksel saraylar, modern gökdelenler, çılgın gece hayatı ve dünya mutfağıyla Asya\'nın en dinamik şehirlerinden biri.',
    highlights: ['Gyeongbokgung Sarayı', 'Bukchon Hanok Köyü', 'Myeongdong', 'Hongdae', 'N Seoul Tower'],
    bestTimeToVisit: 'Mart - Mayıs, Eylül - Kasım',
    timezone: 'UTC+9',
    currency: 'Güney Kore Wonu (KRW)',
    language: 'Korece',
    population: '9.7 milyon',
    image: 'https://images.unsplash.com/photo-1538485399081-7191377e8241?w=1200&h=600&fit=crop',
    events: [
      { name: 'Kiraz Çiçeği Festivali', nameEn: 'Cherry Blossom Festival', date: 'Nisan', description: 'Yeouido\'da kiraz çiçeği izleme.' },
      { name: 'Chuseok', nameEn: 'Chuseok', date: 'Eylül/Ekim (Ay takvimine göre)', description: 'Kore şükran günü, geleneksel kutlamalar.' },
      { name: 'MAMA Awards', nameEn: 'MAMA Awards', date: 'Aralık', description: 'Asya\'nın en büyük K-pop müzik ödülleri.' },
      { name: 'Seoul Lantern Festival', nameEn: 'Seoul Lantern Festival', date: 'Kasım', description: 'Cheonggyecheon Deresi\'nde fener festivali.' },
    ],
  },

  // === AMERİKA ===
  'newyork': {
    slug: 'newyork',
    name: 'New York',
    nameEn: 'New York City',
    country: 'ABD',
    countryCode: 'US',
    airportCodes: ['JFK', 'EWR', 'LGA'],
    description: 'New York, "Asla Uyumayan Şehir" ve dünyanın finans, moda ve eğlence merkezi. Özgürlük Heykeli, Times Square, Broadway ve Central Park ile ikonik bir metropol.',
    highlights: ['Times Square', 'Central Park', 'Özgürlük Heykeli', 'Empire State Building', 'Broadway'],
    bestTimeToVisit: 'Nisan - Haziran, Eylül - Kasım',
    timezone: 'UTC-5',
    currency: 'Amerikan Doları (USD)',
    language: 'İngilizce',
    population: '8.3 milyon',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1200&h=600&fit=crop',
    events: [
      { name: 'Yılbaşı Times Square', nameEn: 'Times Square New Year\'s Eve', date: '31 Aralık', description: 'Dünyaca ünlü top düşürme töreni.' },
      { name: 'Macy\'s Thanksgiving Parade', nameEn: 'Macy\'s Parade', date: 'Kasım (4. Perşembe)', description: 'Dev balonlarla ünlü Şükran Günü geçit töreni.' },
      { name: 'NYC Marathon', nameEn: 'NYC Marathon', date: 'Kasım ilk Pazar', description: 'Dünyanın en büyük maratonu.' },
      { name: 'US Open', nameEn: 'US Open', date: 'Ağustos 25 - Eylül 7', description: 'Grand Slam tenis turnuvası.' },
    ],
  },

  // === BALKANLAR ===
  'belgrad': {
    slug: 'belgrad',
    name: 'Belgrad',
    nameEn: 'Belgrade',
    country: 'Sırbistan',
    countryCode: 'RS',
    airportCodes: ['BEG'],
    description: 'Belgrad, Sırbistan\'ın başkenti ve Balkanların gece hayatı merkezi. Tuna ve Sava nehirlerinin buluştuğu noktada, tarihi kaleleri, nehir boyundaki barları ve uygun fiyatlarıyla tanınır.',
    highlights: ['Kalemegdan Kalesi', 'Skadarlija', 'Knez Mihailova', 'Ada Ciganlija', 'Savamala'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+1',
    currency: 'Sırp Dinarı (RSD)',
    language: 'Sırpça',
    population: '1.4 milyon',
    image: 'https://images.unsplash.com/photo-1592906209472-a36b1f3782ef?w=1200&h=600&fit=crop',
    events: [
      { name: 'EXIT Festival', nameEn: 'EXIT Festival', date: 'Temmuz 10-13', description: 'Avrupa\'nın en iyi festivallerinden biri, Petrovaradin Kalesi\'nde.' },
      { name: 'Belgrade Beer Fest', nameEn: 'Belgrade Beer Fest', date: 'Ağustos', description: 'Güneydoğu Avrupa\'nın en büyük bira festivali.' },
      { name: 'Belgrade Design Week', nameEn: 'Belgrade Design Week', date: 'Haziran', description: 'Balkanların tasarım ve yaratıcılık buluşması.' },
    ],
  },
  'sarajevo': {
    slug: 'sarajevo',
    name: 'Saraybosna',
    nameEn: 'Sarajevo',
    country: 'Bosna Hersek',
    countryCode: 'BA',
    airportCodes: ['SJJ'],
    description: 'Saraybosna, Bosna Hersek\'in başkenti ve Doğu ile Batı\'nın buluştuğu büyülü şehir. Osmanlı ve Avusturya-Macaristan mirasını birlikte yaşatan, tarihi çarşısı ve misafirperverliğiyle tanınır.',
    highlights: ['Baščaršija', 'Latin Köprüsü', 'Gazi Hüsrev Bey Camii', 'Viječnica', 'Bobsled Pisti'],
    bestTimeToVisit: 'Mayıs - Eylül',
    timezone: 'UTC+1',
    currency: 'Bosna Hersek Markı (BAM)',
    language: 'Boşnakça',
    population: '280 bin',
    image: 'https://images.unsplash.com/photo-1586861635167-e5223aadc9fe?w=1200&h=600&fit=crop',
    events: [
      { name: 'Sarajevo Film Festivali', nameEn: 'Sarajevo Film Festival', date: 'Ağustos 15-22', description: 'Güneydoğu Avrupa\'nın en prestijli film festivali.' },
      { name: 'Baščaršija Geceleri', nameEn: 'Baščaršija Nights', date: 'Temmuz', description: 'Eski şehirde kültür ve sanat etkinlikleri.' },
    ],
  },

  // === VİZESİZ ===
  'marakes': {
    slug: 'marakes',
    name: 'Marakeş',
    nameEn: 'Marrakech',
    country: 'Fas',
    countryCode: 'MA',
    airportCodes: ['RAK'],
    description: 'Marakeş, "Kızıl Şehir" olarak bilinen Fas\'ın en büyülü destinasyonu. Jemaa el-Fnaa meydanı, tarihi medina, baharat pazarları ve lüks riad\'larıyla binbir gece masallarını yaşatan şehir.',
    highlights: ['Jemaa el-Fnaa', 'Majorelle Bahçesi', 'Bahia Sarayı', 'Medina Sukları', 'Koutoubia Camii'],
    bestTimeToVisit: 'Mart - Mayıs, Eylül - Kasım',
    timezone: 'UTC+0',
    currency: 'Fas Dirhemi (MAD)',
    language: 'Arapça, Fransızca',
    population: '930 bin',
    image: 'https://images.unsplash.com/photo-1597212618440-806262de4f6b?w=1200&h=600&fit=crop',
    events: [
      { name: 'Marrakech International Film Festival', nameEn: 'Marrakech Film Festival', date: 'Aralık', description: 'Afrika\'nın en prestijli film festivali.' },
      { name: 'Marrakech Popular Arts Festival', nameEn: 'Popular Arts Festival', date: 'Temmuz', description: 'Geleneksel Fas sanatları ve müziği.' },
    ],
  },
  'zanzibar': {
    slug: 'zanzibar',
    name: 'Zanzibar',
    nameEn: 'Zanzibar',
    country: 'Tanzanya',
    countryCode: 'TZ',
    airportCodes: ['ZNZ'],
    description: 'Zanzibar, Hint Okyanusu\'ndaki egzotik ada cenneti. Beyaz kumlu plajlar, turkuaz sular, baharat turları ve tarihi Stone Town\'ıyla Afrika\'nın en romantik destinasyonu.',
    highlights: ['Stone Town', 'Prison Island', 'Nungwi Beach', 'Baharat Turları', 'Jozani Ormanı'],
    bestTimeToVisit: 'Haziran - Ekim, Aralık - Şubat',
    timezone: 'UTC+3',
    currency: 'Tanzanya Şilini (TZS)',
    language: 'Swahili, Arapça, İngilizce',
    population: '1.3 milyon',
    image: 'https://images.unsplash.com/photo-1593693411515-c20261bcad6e?w=1200&h=600&fit=crop',
    events: [
      { name: 'Zanzibar International Film Festival', nameEn: 'ZIFF', date: 'Haziran-Temmuz', description: 'Afrika ve Asya sinemasının buluşması.' },
      { name: 'Sauti za Busara', nameEn: 'Sauti za Busara', date: 'Şubat', description: 'Doğu Afrika\'nın en büyük müzik festivali.' },
      { name: 'Mwaka Kogwa', nameEn: 'Mwaka Kogwa', date: 'Temmuz', description: 'Zanzibar yeni yılı, geleneksel dövüş ve dans.' },
    ],
  },
};

// Get all cities
export function getAllCities(): CityInfo[] {
  return Object.values(cityData);
}

// Get city by slug
export function getCityBySlug(slug: string): CityInfo | null {
  return cityData[slug] || null;
}

// Generate city routes from flight routes
export function getCityFlightRoutes(citySlug: string, flightRoutes: { origin: string; destination: string; slug: string }[]): typeof flightRoutes {
  const city = cityData[citySlug];
  if (!city) return [];
  
  return flightRoutes.filter(route => 
    city.airportCodes.includes(route.origin) || 
    city.airportCodes.includes(route.destination)
  );
}
