// Additional hotels for major destinations - Part 2
// This file expands the hotel data for SEO and static pages

import { HotelData } from './hotels';

// ========== ADDITIONAL ISTANBUL HOTELS ==========
export const istanbulHotelsExpanded: HotelData[] = [
  {
    slug: 'raffles-istanbul',
    name: 'Raffles Istanbul',
    citySlug: 'istanbul',
    summary: 'Zorlu Center\'da bulunan ultra lüks otel. Boğaz manzarası, dünya standartlarında spa ve Michelin seviyesi restoran.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Concierge', 'Butler Servisi'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    address: 'Zorlu Center, Beşiktaş',
    neighborhood: 'Beşiktaş',
    rating: 4.9,
    reviewCount: 1420,
    priceRange: { min: 18000, max: 55000, currency: 'TRY' },
    highlights: ['Zorlu Center entegrasyonu', 'Butler servisi', 'Boğaz manzarası'],
    suitableFor: ['Ultra lüks', 'İş seyahati', 'Özel günler'],
    reasonsToChoose: [
      'Zorlu Center alışveriş ve sanat merkezine entegre',
      'Her odada özel butler hizmeti',
      'İstanbul\'un en modern lüks adresi'
    ],
  },
  {
    slug: 'st-regis-istanbul',
    name: 'The St. Regis Istanbul',
    citySlug: 'istanbul',
    summary: 'Nişantaşı\'nın kalbinde bulunan prestijli otel. Klasik zarafet ve modern lüksün buluşma noktası.',
    stars: 5,
    amenities: ['Spa', 'Fitness', 'Restoran', 'Bar', 'Butler Servisi', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: 'Mim Kemal Öke Cad. No:35, Nişantaşı',
    neighborhood: 'Nişantaşı',
    rating: 4.8,
    reviewCount: 980,
    priceRange: { min: 12000, max: 40000, currency: 'TRY' },
    highlights: ['Nişantaşı lokasyonu', 'St. Regis butler', 'Lüks alışveriş'],
    suitableFor: ['Moda tutkunları', 'Lüks sevenler', 'İş seyahati'],
    reasonsToChoose: [
      'İstanbul\'un en şık semtinde konum',
      'St. Regis imzalı butler servisi',
      'Abdi İpekçi Caddesi\'ne yürüme mesafesi'
    ],
  },
  {
    slug: 'shangri-la-bosphorus-istanbul',
    name: 'Shangri-La Bosphorus Istanbul',
    citySlug: 'istanbul',
    summary: 'Beşiktaş\'ta Boğaz\'ın kenarında Asya zarafeti. Muhteşem deniz manzarası ve Uzak Doğu misafirperverliği.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Teras', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    address: 'Sinanpaşa Mah., Beşiktaş',
    neighborhood: 'Beşiktaş',
    rating: 4.8,
    reviewCount: 1650,
    priceRange: { min: 14000, max: 45000, currency: 'TRY' },
    highlights: ['Boğaz manzarası', 'Asya misafirperverliği', 'CHI Spa'],
    suitableFor: ['Wellness arayanlar', 'Romantik tatil', 'İş seyahati'],
    reasonsToChoose: [
      'Boğaz\'a sıfır eşsiz lokasyon',
      'Ödüllü CHI Spa deneyimi',
      'Asya-Akdeniz fusion mutfağı'
    ],
  },
  {
    slug: 'pera-palace-hotel-istanbul',
    name: 'Pera Palace Hotel',
    citySlug: 'istanbul',
    summary: 'Orient Express yolcularının efsanevi durağı. Agatha Christie\'nin "Doğu Ekspresinde Cinayet"i yazdığı tarihi otel.',
    stars: 5,
    amenities: ['Spa', 'Restoran', 'Bar', 'Müze', 'Concierge', 'Tarihi Tur'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    address: 'Meşrutiyet Cad. No:52, Tepebaşı',
    neighborhood: 'Beyoğlu',
    rating: 4.7,
    reviewCount: 2100,
    priceRange: { min: 8000, max: 25000, currency: 'TRY' },
    highlights: ['Tarihi miras', 'Agatha Christie odası', 'Orient Express'],
    suitableFor: ['Tarih meraklıları', 'Romantik tatil', 'Kültür turistleri'],
    reasonsToChoose: [
      '130 yılı aşkın tarihi miras',
      'Agatha Christie ve Atatürk\'ün kaldığı odalar',
      'Orient Express\'in efsanevi durağı'
    ],
  },
  {
    slug: 'ajwa-hotel-sultanahmet-istanbul',
    name: 'Ajwa Hotel Sultanahmet',
    citySlug: 'istanbul',
    summary: 'Sultanahmet\'te Osmanlı saray konseptinde ultra lüks butik otel. Ayasofya manzaralı odalar ve özel hamam.',
    stars: 5,
    amenities: ['Hamam', 'Spa', 'Restoran', 'Bar', 'Teras', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'],
    address: 'Küçük Ayasofya Mah., Sultanahmet',
    neighborhood: 'Sultanahmet',
    rating: 4.8,
    reviewCount: 890,
    priceRange: { min: 10000, max: 30000, currency: 'TRY' },
    highlights: ['Ayasofya manzarası', 'Osmanlı konsepti', 'Özel hamam'],
    suitableFor: ['Tarihi deneyim arayanlar', 'Balayı', 'Lüks sevenler'],
    reasonsToChoose: [
      'Sultanahmet\'in tam kalbinde eşsiz konum',
      'Osmanlı saray estetiği ile modern konfor',
      'Ayasofya manzaralı çatı restoranı'
    ],
  },
  {
    slug: 'ritz-carlton-istanbul',
    name: 'The Ritz-Carlton Istanbul',
    citySlug: 'istanbul',
    summary: 'Şişli\'de Boğaz ve şehir manzaralı lüks otel. Ritz-Carlton standartları ve merkezi konum.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    address: 'Suzer Plaza, Elmadag, Şişli',
    neighborhood: 'Şişli',
    rating: 4.7,
    reviewCount: 1890,
    priceRange: { min: 8000, max: 28000, currency: 'TRY' },
    highlights: ['Boğaz manzarası', 'Merkezi konum', 'Ritz-Carlton kalitesi'],
    suitableFor: ['İş seyahati', 'Lüks tatil', 'Şehir gezisi'],
    reasonsToChoose: [
      'İstanbul\'un iş merkezine yakın stratejik konum',
      'Dünya standartlarında Ritz-Carlton hizmeti',
      'Panoramik Boğaz manzaralı odalar'
    ],
  },
  {
    slug: 'swissotel-bosphorus-istanbul',
    name: 'Swissôtel The Bosphorus Istanbul',
    citySlug: 'istanbul',
    summary: 'Maçka Parkı\'nın yanında, 65 dönümlük bahçe içinde lüks otel. Şehrin ortasında yeşil vaha.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Bahçe', 'Tenis'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: 'Bayıldım Cad. No:2, Maçka',
    neighborhood: 'Maçka',
    rating: 4.6,
    reviewCount: 2450,
    priceRange: { min: 6000, max: 20000, currency: 'TRY' },
    highlights: ['Geniş bahçe', 'Maçka Parkı', 'Şehir merkezi'],
    suitableFor: ['Aileler', 'İş seyahati', 'Wellness arayanlar'],
    reasonsToChoose: [
      'Şehrin ortasında 65 dönümlük yeşil alan',
      'Maçka Parkı\'na entegre doğa deneyimi',
      'İstanbul\'un en büyük otel spa\'larından biri'
    ],
  },
  {
    slug: 'w-istanbul',
    name: 'W Istanbul',
    citySlug: 'istanbul',
    summary: 'Beşiktaş\'ta tarihi Akaretler Sıraevleri\'nde trendy butik otel. Genç, dinamik ve renkli atmosfer.',
    stars: 5,
    amenities: ['Spa', 'Fitness', 'Restoran', 'Bar', 'Havuz', 'DJ'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    address: 'Suleyman Seba Cad. No:22, Akaretler',
    neighborhood: 'Beşiktaş',
    rating: 4.5,
    reviewCount: 1340,
    priceRange: { min: 7000, max: 22000, currency: 'TRY' },
    highlights: ['Trendy atmosfer', 'Akaretler Sıraevleri', 'Gece hayatı'],
    suitableFor: ['Genç çiftler', 'Sosyal gezginler', 'Trend takipçileri'],
    reasonsToChoose: [
      'Tarihi Akaretler binalarında modern tasarım',
      'İstanbul\'un en canlı gece hayatına yakın',
      'W markasının dinamik ve renkli tarzı'
    ],
  },
  {
    slug: 'hotel-niles-istanbul',
    name: 'Hotel Niles Istanbul',
    citySlug: 'istanbul',
    summary: 'Beyoğlu\'nda butik ve samimi bir konaklama. Galata Kulesi\'ne yakın, şık tasarım.',
    stars: 4,
    amenities: ['WiFi', 'Bar', 'Restoran', 'Teras', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    address: 'Bereketzade Mah., Galata',
    neighborhood: 'Galata',
    rating: 4.4,
    reviewCount: 670,
    priceRange: { min: 3000, max: 8000, currency: 'TRY' },
    highlights: ['Galata Kulesi yakını', 'Butik atmosfer', 'Beyoğlu merkez'],
    suitableFor: ['Çiftler', 'Kültür turistleri', 'Butik otel arayanlar'],
    reasonsToChoose: [
      'Galata Kulesi\'ne yürüyerek 2 dakika',
      'Samimi butik otel atmosferi',
      'İstanbul\'un tarihi ve modern yüzünün kesişimi'
    ],
  },
  {
    slug: 'ada-hotel-istanbul',
    name: 'Ada Hotel Istanbul',
    citySlug: 'istanbul',
    summary: 'Büyükada\'da tarihi köşkte konaklama. Arabası olmayan adada huzurlu bir kaçış.',
    stars: 4,
    amenities: ['Bahçe', 'Restoran', 'Teras', 'Bisiklet', 'WiFi'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: 'Nizam Cad., Büyükada',
    neighborhood: 'Büyükada',
    rating: 4.6,
    reviewCount: 450,
    priceRange: { min: 4000, max: 12000, currency: 'TRY' },
    highlights: ['Ada huzuru', 'Tarihi köşk', 'Doğa'],
    suitableFor: ['Romantik kaçamak', 'Doğa severler', 'Huzur arayanlar'],
    reasonsToChoose: [
      'Şehir gürültüsünden uzak ada huzuru',
      '19. yüzyıldan restore edilmiş tarihi köşk',
      'Arabasız adada bisiklet ve fayton nostalji'
    ],
  },
];

// ========== ADDITIONAL ANTALYA HOTELS ==========
export const antalyaHotelsExpanded: HotelData[] = [
  {
    slug: 'maxx-royal-belek-antalya',
    name: 'Maxx Royal Belek Golf Resort',
    citySlug: 'antalya',
    summary: 'Belek\'te ultra her şey dahil konseptinde lüks resort. Özel plaj, su parkı ve championship golf.',
    stars: 5,
    amenities: ['Golf', 'Havuz', 'Spa', 'Aquapark', 'Özel Plaj', 'Kids Club', 'Restoran'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    address: 'Üçkum Tepesi Mevkii, Belek',
    neighborhood: 'Belek',
    rating: 4.9,
    reviewCount: 2100,
    priceRange: { min: 35000, max: 90000, currency: 'TRY' },
    highlights: ['Ultra lüks her şey dahil', 'Championship golf', 'Su parkı'],
    suitableFor: ['Aileler', 'Golf tutkunları', 'Ultra lüks tatil'],
    reasonsToChoose: [
      'Türkiye\'nin en kapsamlı her şey dahil konsepti',
      'PGA standartlarında golf sahası',
      'Çocuklar için ayrı havuz ve aktivite alanları'
    ],
  },
  {
    slug: 'rixos-premium-belek-antalya',
    name: 'Rixos Premium Belek',
    citySlug: 'antalya',
    summary: 'Belek\'te Akdeniz\'e sıfır ultra lüks resort. Her şey dahil konseptiyle dünya standartları.',
    stars: 5,
    amenities: ['Havuz', 'Spa', 'Fitness', 'Özel Plaj', 'Aquapark', 'Kids Club', 'Golf'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: 'İleribaşı Mevkii, Belek',
    neighborhood: 'Belek',
    rating: 4.8,
    reviewCount: 3450,
    priceRange: { min: 20000, max: 55000, currency: 'TRY' },
    highlights: ['Denize sıfır', 'Ultra her şey dahil', 'Animasyon'],
    suitableFor: ['Aileler', 'Çiftler', 'Her şey dahil sevenler'],
    reasonsToChoose: [
      'Türk Rivierası\'nın en bilinen markası',
      '700 metre özel kum plajı',
      '24 saat ultra her şey dahil hizmet'
    ],
  },
  {
    slug: 'calista-luxury-resort-antalya',
    name: 'Calista Luxury Resort',
    citySlug: 'antalya',
    summary: 'Belek\'te botanik bahçe konseptinde lüks resort. Osmanlı ve modern tasarımın buluşması.',
    stars: 5,
    amenities: ['Havuz', 'Spa', 'Fitness', 'Özel Plaj', 'Golf', 'Kids Club', 'Aquapark'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    address: 'Kadriye Mahallesi, Belek',
    neighborhood: 'Belek',
    rating: 4.7,
    reviewCount: 1890,
    priceRange: { min: 18000, max: 45000, currency: 'TRY' },
    highlights: ['Botanik bahçe', 'Osmanlı mimarisi', 'Premium hizmet'],
    suitableFor: ['Doğa severler', 'Aileler', 'Lüks tatilciler'],
    reasonsToChoose: [
      'Eşsiz botanik bahçe konsepti',
      'Osmanlı saray mimarisinden esinlenen tasarım',
      'Kişiselleştirilmiş butik hizmet anlayışı'
    ],
  },
  {
    slug: 'gloria-serenity-resort-antalya',
    name: 'Gloria Serenity Resort',
    citySlug: 'antalya',
    summary: 'Belek\'te huzur ve lüksün buluştuğu resort. Yetişkinlere özel bölümler ve golf.',
    stars: 5,
    amenities: ['Golf', 'Havuz', 'Spa', 'Fitness', 'Özel Plaj', 'Restoran'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    address: 'Acısu Mevkii, Belek',
    neighborhood: 'Belek',
    rating: 4.7,
    reviewCount: 1560,
    priceRange: { min: 15000, max: 40000, currency: 'TRY' },
    highlights: ['Yetişkin odaklı', 'Golf merkezi', 'Huzurlu atmosfer'],
    suitableFor: ['Çiftler', 'Golf tutkunları', 'Huzur arayanlar'],
    reasonsToChoose: [
      'Yetişkinlere özel sakin bölümler',
      '45 çukurlu golf sahası kompleksi',
      'Akdeniz\'in en güzel plajlarından biri'
    ],
  },
  {
    slug: 'susesi-luxury-resort-antalya',
    name: 'Susesi Luxury Resort',
    citySlug: 'antalya',
    summary: 'Belek\'te aile dostu ultra lüks resort. Geniş aquapark ve çocuk aktiviteleri.',
    stars: 5,
    amenities: ['Aquapark', 'Havuz', 'Spa', 'Kids Club', 'Özel Plaj', 'Bowling'],
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'],
    address: 'İskele Mevkii, Belek',
    neighborhood: 'Belek',
    rating: 4.6,
    reviewCount: 2340,
    priceRange: { min: 12000, max: 35000, currency: 'TRY' },
    highlights: ['Büyük aquapark', 'Aile dostu', 'Eğlence merkezi'],
    suitableFor: ['Aileler', 'Çocuklu tatil', 'Eğlence arayanlar'],
    reasonsToChoose: [
      'Bölgenin en büyük su parkı',
      'Çocuklar için 7/24 aktivite programı',
      'Aile odaklı tesis tasarımı'
    ],
  },
  {
    slug: 'delphin-imperial-antalya',
    name: 'Delphin Imperial',
    citySlug: 'antalya',
    summary: 'Lara\'da denize sıfır mega resort. Geniş havuz alanları ve canlı animasyon.',
    stars: 5,
    amenities: ['Havuz', 'Spa', 'Fitness', 'Özel Plaj', 'Aquapark', 'Tenis', 'Bowling'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    address: 'Lara Turizm Merkezi, Lara',
    neighborhood: 'Lara',
    rating: 4.6,
    reviewCount: 4560,
    priceRange: { min: 10000, max: 28000, currency: 'TRY' },
    highlights: ['Lara plajı', 'Mega tesis', 'Animasyon'],
    suitableFor: ['Aileler', 'Genç çiftler', 'Eğlence sevenler'],
    reasonsToChoose: [
      'Lara\'nın en popüler otellerinden biri',
      'Dünya standartlarında animasyon ekibi',
      'Çeşitli restoran ve bar seçenekleri'
    ],
  },
  {
    slug: 'club-hotel-sera-antalya',
    name: 'Club Hotel Sera',
    citySlug: 'antalya',
    summary: 'Lara\'da sahil şeridinde her şey dahil otel. Uygun fiyata kaliteli tatil.',
    stars: 5,
    amenities: ['Havuz', 'Spa', 'Fitness', 'Özel Plaj', 'Kids Club', 'Restoran'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: 'Lara Cad., Lara',
    neighborhood: 'Lara',
    rating: 4.4,
    reviewCount: 3200,
    priceRange: { min: 6000, max: 18000, currency: 'TRY' },
    highlights: ['Değer/fiyat', 'Lara plajı', 'Aile dostu'],
    suitableFor: ['Bütçe bilincli aileler', 'Grup tatili', 'İlk kez Antalya'],
    reasonsToChoose: [
      'Kaliteli her şey dahil uygun fiyata',
      'Lara sahil şeridinin merkezinde',
      'Güler yüzlü personel ve samimi atmosfer'
    ],
  },
  {
    slug: 'hillside-su-antalya',
    name: 'Hillside Su',
    citySlug: 'antalya',
    summary: 'Antalya şehir merkezinde tasarım oteli. Plaj kulübü ve şık atmosfer.',
    stars: 5,
    amenities: ['Havuz', 'Spa', 'Beach Club', 'Restoran', 'Bar', 'Fitness'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    address: 'Konyaaltı Cad., Konyaaltı',
    neighborhood: 'Konyaaltı',
    rating: 4.5,
    reviewCount: 890,
    priceRange: { min: 7000, max: 20000, currency: 'TRY' },
    highlights: ['Tasarım otel', 'Beach club', 'Şehir merkezi'],
    suitableFor: ['Tasarım tutkunları', 'Genç çiftler', 'Şehir tatili'],
    reasonsToChoose: [
      'Türkiye\'nin ilk tasarım otellerinden biri',
      'Konyaaltı sahilinde özel beach club',
      'Şehir merkezine ve tarihi yerlere yakın'
    ],
  },
  {
    slug: 'voyage-belek-antalya',
    name: 'Voyage Belek Golf & Spa',
    citySlug: 'antalya',
    summary: 'Belek\'te golf odaklı lüks resort. Nick Faldo tasarımı saha ve wellness merkezi.',
    stars: 5,
    amenities: ['Golf', 'Spa', 'Havuz', 'Fitness', 'Özel Plaj', 'Kids Club'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    address: 'İleribaşı Mevkii, Belek',
    neighborhood: 'Belek',
    rating: 4.7,
    reviewCount: 1670,
    priceRange: { min: 16000, max: 42000, currency: 'TRY' },
    highlights: ['Nick Faldo golf', 'Wellness', 'Premium hizmet'],
    suitableFor: ['Golf tutkunları', 'Wellness arayanlar', 'Spor tatili'],
    reasonsToChoose: [
      'Nick Faldo imzalı championship golf sahası',
      'Kapsamlı wellness ve detox programları',
      'Spor odaklı aktif tatil konsepti'
    ],
  },
  {
    slug: 'tui-blue-palm-garden-antalya',
    name: 'TUI BLUE Palm Garden',
    citySlug: 'antalya',
    summary: 'Manavgat\'ta aile dostu resort. Geniş yeşil alanlar ve Side antik kente yakın.',
    stars: 5,
    amenities: ['Havuz', 'Spa', 'Kids Club', 'Fitness', 'Özel Plaj', 'Tenis'],
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'],
    address: 'Titreyengöl Mevkii, Manavgat',
    neighborhood: 'Manavgat',
    rating: 4.5,
    reviewCount: 2100,
    priceRange: { min: 8000, max: 22000, currency: 'TRY' },
    highlights: ['Yeşil alan', 'Side yakını', 'Aile dostu'],
    suitableFor: ['Aileler', 'Doğa severler', 'Tarih meraklıları'],
    reasonsToChoose: [
      'Geniş palmiye bahçeleri içinde huzurlu konum',
      'Side antik kentine kolay ulaşım',
      'TUI\'nin kalite standartları garantisi'
    ],
  },
];

// ========== ADDITIONAL DUBAI HOTELS ==========
export const dubaiHotelsExpanded: HotelData[] = [
  {
    slug: 'atlantis-the-palm-dubai',
    name: 'Atlantis The Palm',
    citySlug: 'dubai',
    summary: 'Palm Jumeirah\'ın ikonik oteli. Aquaventure su parkı, kayıp şehir konsepti ve underwater suite.',
    stars: 5,
    amenities: ['Aquapark', 'Havuz', 'Spa', 'Akvaryum', 'Özel Plaj', 'Restoran', 'Kids Club'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    address: 'Crescent Rd, Palm Jumeirah, Dubai',
    neighborhood: 'Palm Jumeirah',
    rating: 4.7,
    reviewCount: 8900,
    priceRange: { min: 15000, max: 150000, currency: 'TRY' },
    highlights: ['Aquaventure', 'Underwater suite', 'The Lost Chambers'],
    suitableFor: ['Aileler', 'Çiftler', 'Eğlence arayanlar'],
    reasonsToChoose: [
      'Dünyanın en iyi su parklarından Aquaventure',
      'The Lost Chambers akvaryumu ile deniz yaşamı',
      'Underwater suite ile benzersiz konaklama'
    ],
  },
  {
    slug: 'one-only-the-palm-dubai',
    name: 'One&Only The Palm',
    citySlug: 'dubai',
    summary: 'Palm Jumeirah\'da ultra lüks butik resort. Özel villalar, Guerlain Spa ve mahremiyat.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Özel Plaj', 'Restoran', 'Butler Servisi', 'Marina'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: 'West Crescent, Palm Jumeirah, Dubai',
    neighborhood: 'Palm Jumeirah',
    rating: 4.9,
    reviewCount: 1450,
    priceRange: { min: 30000, max: 200000, currency: 'TRY' },
    highlights: ['Özel villa', 'Guerlain Spa', 'Yüksek mahremiyet'],
    suitableFor: ['Ultra lüks', 'Balayı', 'Ünlüler'],
    reasonsToChoose: [
      'Palm\'ın en mahremiyet odaklı resortu',
      'Dünyaca ünlü Guerlain Spa',
      'Sadece 90 oda ile butik deneyim'
    ],
  },
  {
    slug: 'jumeirah-al-qasr-dubai',
    name: 'Jumeirah Al Qasr',
    citySlug: 'dubai',
    summary: 'Madinat Jumeirah\'da Arap saray konseptinde resort. Burj Al Arab manzarası ve su kanalları.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Özel Plaj', 'Abra Teknesi', 'Souk', 'Restoran'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    address: 'Madinat Jumeirah, Dubai',
    neighborhood: 'Madinat Jumeirah',
    rating: 4.8,
    reviewCount: 2340,
    priceRange: { min: 18000, max: 80000, currency: 'TRY' },
    highlights: ['Arap sarayı', 'Burj Al Arab manzarası', 'Su kanalları'],
    suitableFor: ['Kültür meraklıları', 'Romantik tatil', 'Lüks sevenler'],
    reasonsToChoose: [
      'Geleneksel Arap saray mimarisi',
      'Abra teknesiyle Madinat Jumeirah turu',
      'Burj Al Arab\'a yürüme mesafesi'
    ],
  },
  {
    slug: 'address-downtown-dubai',
    name: 'Address Downtown',
    citySlug: 'dubai',
    summary: 'Burj Khalifa ve Dubai Mall\'a bitişik lüks otel. Şehrin kalbinde dinamik konum.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    address: 'Sheikh Mohammed bin Rashid Blvd, Downtown Dubai',
    neighborhood: 'Downtown Dubai',
    rating: 4.7,
    reviewCount: 3560,
    priceRange: { min: 12000, max: 45000, currency: 'TRY' },
    highlights: ['Burj Khalifa yanı', 'Dubai Mall', 'Şehir merkezi'],
    suitableFor: ['Şehir tatili', 'Alışveriş', 'İş seyahati'],
    reasonsToChoose: [
      'Burj Khalifa\'ya direkt bağlantı',
      'Dubai Mall\'a özel koridor',
      'Dubai Fountain manzarası'
    ],
  },
  {
    slug: 'armani-hotel-dubai',
    name: 'Armani Hotel Dubai',
    citySlug: 'dubai',
    summary: 'Burj Khalifa içinde Giorgio Armani imzalı otel. Minimalist lüks ve ikonik lokasyon.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'],
    address: 'Burj Khalifa, Downtown Dubai',
    neighborhood: 'Downtown Dubai',
    rating: 4.8,
    reviewCount: 1890,
    priceRange: { min: 20000, max: 100000, currency: 'TRY' },
    highlights: ['Burj Khalifa içi', 'Armani tasarımı', 'Minimalist lüks'],
    suitableFor: ['Moda tutkunları', 'Ultra lüks', 'Mimari meraklıları'],
    reasonsToChoose: [
      'Dünyanın en yüksek binasında konaklama',
      'Giorgio Armani\'nin kişisel tasarımları',
      'Burj Khalifa\'nın alt 39 katında özel erişim'
    ],
  },
  {
    slug: 'four-seasons-dubai-jumeirah',
    name: 'Four Seasons Resort Dubai at Jumeirah Beach',
    citySlug: 'dubai',
    summary: 'Jumeirah Beach\'te aile dostu lüks resort. Özel plaj ve çocuk aktiviteleri.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Özel Plaj', 'Kids Club', 'Fitness', 'Restoran'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    address: 'Jumeirah Road, Jumeirah 2, Dubai',
    neighborhood: 'Jumeirah',
    rating: 4.8,
    reviewCount: 2100,
    priceRange: { min: 15000, max: 60000, currency: 'TRY' },
    highlights: ['Jumeirah Beach', 'Aile dostu', 'Four Seasons'],
    suitableFor: ['Aileler', 'Plaj tatili', 'Lüks sevenler'],
    reasonsToChoose: [
      'Dubai\'nin en güzel kum plajlarından biri',
      'Çocuklar için özel programlar ve aktiviteler',
      'Four Seasons\'ın dünya standartları'
    ],
  },
  {
    slug: 'raffles-dubai',
    name: 'Raffles Dubai',
    citySlug: 'dubai',
    summary: 'Wafi City\'de piramit şeklinde ikonik bina. Antik Mısır\'dan ilham alan tasarım.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Butler Servisi'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: 'Sheikh Rashid Road, Wafi City, Dubai',
    neighborhood: 'Wafi',
    rating: 4.7,
    reviewCount: 1560,
    priceRange: { min: 10000, max: 50000, currency: 'TRY' },
    highlights: ['Piramit bina', 'Mısır teması', 'Butler servisi'],
    suitableFor: ['Tasarım tutkunları', 'İş seyahati', 'Lüks sevenler'],
    reasonsToChoose: [
      'Dubai\'nin en benzersiz otel mimarisi',
      'Wafi alışveriş merkezine entegre',
      'Her odada Raffles butler hizmeti'
    ],
  },
  {
    slug: 'waldorf-astoria-palm-jumeirah-dubai',
    name: 'Waldorf Astoria Dubai Palm Jumeirah',
    citySlug: 'dubai',
    summary: 'Palm Jumeirah\'da Art Deco ilhamlı lüks resort. Özel plaj ve zarif tasarım.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Özel Plaj', 'Fitness', 'Restoran', 'Bar'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    address: 'Crescent Rd, Palm Jumeirah, Dubai',
    neighborhood: 'Palm Jumeirah',
    rating: 4.8,
    reviewCount: 1890,
    priceRange: { min: 14000, max: 55000, currency: 'TRY' },
    highlights: ['Art Deco tasarım', 'Palm Jumeirah', 'Zarif atmosfer'],
    suitableFor: ['Çiftler', 'Lüks sevenler', 'Romantik tatil'],
    reasonsToChoose: [
      'Palm\'ın en zarif otellerinden biri',
      '1930\'lar New York\'undan esinlenen Art Deco tasarım',
      'Özel plajda gün batımı manzarası'
    ],
  },
  {
    slug: 'ritz-carlton-dubai',
    name: 'The Ritz-Carlton Dubai',
    citySlug: 'dubai',
    summary: 'JBR\'de Akdeniz tarzı beach resort. Yat limanı manzarası ve lüks plaj deneyimi.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Özel Plaj', 'Fitness', 'Restoran', 'Marina'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    address: 'JBR The Walk, Dubai',
    neighborhood: 'JBR',
    rating: 4.7,
    reviewCount: 2340,
    priceRange: { min: 12000, max: 50000, currency: 'TRY' },
    highlights: ['JBR lokasyonu', 'Marina manzarası', 'Akdeniz stili'],
    suitableFor: ['Plaj tatili', 'Aileler', 'Lüks sevenler'],
    reasonsToChoose: [
      'JBR\'nin en prestijli adresi',
      'Dubai Marina yat limanı manzarası',
      'Akdeniz esintili rahatlatıcı tasarım'
    ],
  },
  {
    slug: 'palace-downtown-dubai',
    name: 'Palace Downtown',
    citySlug: 'dubai',
    summary: 'Downtown Dubai\'da Arap mimarisinden ilham alan saray otel. Burj Khalifa manzarası.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Restoran', 'Bar', 'Fitness', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'],
    address: 'Sheikh Mohammed bin Rashid Blvd, Downtown Dubai',
    neighborhood: 'Downtown Dubai',
    rating: 4.8,
    reviewCount: 2100,
    priceRange: { min: 14000, max: 55000, currency: 'TRY' },
    highlights: ['Arap sarayı', 'Burj Khalifa manzarası', 'Old Town'],
    suitableFor: ['Romantik tatil', 'Kültür meraklıları', 'Özel günler'],
    reasonsToChoose: [
      'Dubai Fountain ve Burj Khalifa manzarası',
      'Old Town Souk\'a entegre alışveriş',
      'Geleneksel Arap misafirperverliği'
    ],
  },
];

// ========== ADDITIONAL TOKYO HOTELS ==========
export const tokyoHotelsExpanded: HotelData[] = [
  {
    slug: 'aman-tokyo',
    name: 'Aman Tokyo',
    citySlug: 'tokyo',
    summary: 'Otemachi\'de gökyüzü lobi ile ultra lüks otel. Japon minimalizmi ve şehir manzarası.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Onsen'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    address: 'The Otemachi Tower, 1-5-6 Otemachi, Chiyoda-ku, Tokyo',
    neighborhood: 'Otemachi',
    rating: 4.9,
    reviewCount: 890,
    priceRange: { min: 40000, max: 200000, currency: 'TRY' },
    highlights: ['Aman servisi', 'Japon minimalizmi', 'Şehir manzarası'],
    suitableFor: ['Ultra lüks', 'Wellness arayanlar', 'Romantik kaçamak'],
    reasonsToChoose: [
      'Dünyanın en prestijli otel markası Aman',
      'Japon estetiği ile modern lüksün buluşması',
      'Şehrin merkezinde özel onsen deneyimi'
    ],
  },
  {
    slug: 'mandarin-oriental-tokyo',
    name: 'Mandarin Oriental Tokyo',
    citySlug: 'tokyo',
    summary: 'Nihonbashi\'de panoramik şehir manzaralı lüks otel. Michelin yıldızlı restoranlar.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Michelin Restoran', 'Bar', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: '2-1-1 Nihonbashi Muromachi, Chuo-ku, Tokyo',
    neighborhood: 'Nihonbashi',
    rating: 4.8,
    reviewCount: 1560,
    priceRange: { min: 25000, max: 120000, currency: 'TRY' },
    highlights: ['Michelin restoranlar', 'Tokyo skyline', 'Nihonbashi'],
    suitableFor: ['Gurme', 'Lüks sevenler', 'İş seyahati'],
    reasonsToChoose: [
      'Tokyo\'nun en iyi manzaralarından biri',
      'Birden fazla Michelin yıldızlı restoran',
      'Nihonbashi\'nin tarihi atmosferi'
    ],
  },
  {
    slug: 'andaz-tokyo-toranomon-hills',
    name: 'Andaz Tokyo Toranomon Hills',
    citySlug: 'tokyo',
    summary: 'Toranomon Hills\'de modern tasarım oteli. Sanat galerisi atmosferi ve Tokyo manzarası.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Sanat Galerisi'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    address: '1-23-4 Toranomon, Minato-ku, Tokyo',
    neighborhood: 'Toranomon',
    rating: 4.7,
    reviewCount: 1230,
    priceRange: { min: 18000, max: 70000, currency: 'TRY' },
    highlights: ['Modern sanat', 'Toranomon Hills', 'Tasarım'],
    suitableFor: ['Sanat severler', 'İş seyahati', 'Tasarım tutkunları'],
    reasonsToChoose: [
      'Tokyo\'nun yeni iş merkezinde merkezi konum',
      'Japon sanatından esinlenen iç tasarım',
      '52. kattan panoramik manzara'
    ],
  },
  {
    slug: 'the-peninsula-tokyo',
    name: 'The Peninsula Tokyo',
    citySlug: 'tokyo',
    summary: 'Marunouchi\'de İmparatorluk Sarayı\'na bakan ultra lüks otel. Klasik Japon zarafeti.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Helipad'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    address: '1-8-1 Yurakucho, Chiyoda-ku, Tokyo',
    neighborhood: 'Marunouchi',
    rating: 4.9,
    reviewCount: 1780,
    priceRange: { min: 30000, max: 150000, currency: 'TRY' },
    highlights: ['İmparatorluk Sarayı', 'Peninsula servisi', 'Helikopter'],
    suitableFor: ['Ultra lüks', 'İş seyahati', 'Özel günler'],
    reasonsToChoose: [
      'İmparatorluk Sarayı bahçelerine bakan odalar',
      'Peninsula\'nın efsanevi servis standartları',
      'Ginza alışveriş bölgesine yürüme mesafesi'
    ],
  },
  {
    slug: 'hoshinoya-tokyo',
    name: 'Hoshinoya Tokyo',
    citySlug: 'tokyo',
    summary: 'Otemachi\'de geleneksel ryokan konseptinde şehir oteli. Omotenashi ve onsen.',
    stars: 5,
    amenities: ['Onsen', 'Restoran', 'Tatami Odalar', 'Kaiseki', 'Tea Ceremony'],
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'],
    address: '1-9-1 Otemachi, Chiyoda-ku, Tokyo',
    neighborhood: 'Otemachi',
    rating: 4.8,
    reviewCount: 670,
    priceRange: { min: 45000, max: 180000, currency: 'TRY' },
    highlights: ['Ryokan deneyimi', 'Onsen', 'Kaiseki mutfak'],
    suitableFor: ['Japon kültürü meraklıları', 'Wellness', 'Benzersiz deneyim'],
    reasonsToChoose: [
      'Şehrin ortasında otantik ryokan deneyimi',
      'Özel onsen ve geleneksel banyo ritüelleri',
      'Michelin seviyesi kaiseki yemekleri'
    ],
  },
  {
    slug: 'the-ritz-carlton-tokyo',
    name: 'The Ritz-Carlton Tokyo',
    citySlug: 'tokyo',
    summary: 'Roppongi\'de Tokyo Midtown\'da lüks otel. Fuji Dağı ve şehir manzarası.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Michelin Restoran', 'Bar', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    address: '9-7-1 Akasaka, Minato-ku, Tokyo',
    neighborhood: 'Roppongi',
    rating: 4.8,
    reviewCount: 2340,
    priceRange: { min: 28000, max: 130000, currency: 'TRY' },
    highlights: ['Fuji Dağı manzarası', 'Tokyo Midtown', 'Ritz-Carlton'],
    suitableFor: ['Lüks sevenler', 'İş seyahati', 'Romantik tatil'],
    reasonsToChoose: [
      'Açık havalarda Fuji Dağı manzarası',
      'Tokyo Midtown alışveriş ve sanat merkezine entegre',
      '45. kattan başlayan muhteşem panorama'
    ],
  },
  {
    slug: 'conrad-tokyo',
    name: 'Conrad Tokyo',
    citySlug: 'tokyo',
    summary: 'Shiodome\'de Tokyo Körfezi manzaralı modern otel. Hamarikyu bahçeleri yakını.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Concierge'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: '1-9-1 Higashi-Shinbashi, Minato-ku, Tokyo',
    neighborhood: 'Shiodome',
    rating: 4.7,
    reviewCount: 1890,
    priceRange: { min: 18000, max: 80000, currency: 'TRY' },
    highlights: ['Körfez manzarası', 'Hamarikyu yakını', 'Modern tasarım'],
    suitableFor: ['İş seyahati', 'Şehir gezisi', 'Lüks tatil'],
    reasonsToChoose: [
      'Tokyo Körfezi ve Rainbow Köprüsü manzarası',
      'Tarihi Hamarikyu bahçelerine yürüme mesafesi',
      'Ginza ve Tsukiji\'ye kolay ulaşım'
    ],
  },
  {
    slug: 'granbell-hotel-shinjuku-tokyo',
    name: 'Shinjuku Granbell Hotel',
    citySlug: 'tokyo',
    summary: 'Shinjuku\'da tasarım odaklı butik otel. Uygun fiyata şık konaklama.',
    stars: 4,
    amenities: ['WiFi', 'Restoran', 'Bar', 'Fitness', 'Teras'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    address: '2-14-5 Kabukicho, Shinjuku-ku, Tokyo',
    neighborhood: 'Shinjuku',
    rating: 4.3,
    reviewCount: 2560,
    priceRange: { min: 4000, max: 12000, currency: 'TRY' },
    highlights: ['Şık tasarım', 'Shinjuku merkez', 'Uygun fiyat'],
    suitableFor: ['Genç gezginler', 'Bütçe bilincli', 'Şehir gezisi'],
    reasonsToChoose: [
      'Shinjuku istasyonuna yakın merkezi konum',
      'Tasarım odaklı odalar uygun fiyata',
      'Golden Gai ve Kabukicho\'ya yürüme mesafesi'
    ],
  },
  {
    slug: 'the-prince-gallery-tokyo',
    name: 'The Prince Gallery Tokyo Kioicho',
    citySlug: 'tokyo',
    summary: 'Kioicho\'da çağdaş sanat temalı ultra lüks otel. Tokyo manzarası ve sakin atmosfer.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Fitness', 'Restoran', 'Bar', 'Sanat Koleksiyonu'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    address: '1-2 Kioicho, Chiyoda-ku, Tokyo',
    neighborhood: 'Kioicho',
    rating: 4.8,
    reviewCount: 890,
    priceRange: { min: 25000, max: 100000, currency: 'TRY' },
    highlights: ['Çağdaş sanat', 'Sakin lokasyon', 'Lüks tasarım'],
    suitableFor: ['Sanat severler', 'Huzur arayanlar', 'Lüks tatil'],
    reasonsToChoose: [
      'Tokyo\'nun sakin ve prestijli semtinde',
      'Çağdaş sanat koleksiyonu sergileniyor',
      '30. kattan panoramik manzara'
    ],
  },
  {
    slug: 'trunk-hotel-tokyo',
    name: 'TRUNK(HOTEL)',
    citySlug: 'tokyo',
    summary: 'Shibuya\'da sosyal sorumluluk odaklı butik otel. Lokal ve sürdürülebilir konsept.',
    stars: 4,
    amenities: ['WiFi', 'Restoran', 'Bar', 'Lounge', 'Etkinlik Alanı'],
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'],
    address: '5-31 Jingumae, Shibuya-ku, Tokyo',
    neighborhood: 'Shibuya',
    rating: 4.5,
    reviewCount: 780,
    priceRange: { min: 12000, max: 35000, currency: 'TRY' },
    highlights: ['Sürdürülebilir', 'Shibuya lokasyonu', 'Sosyal konsept'],
    suitableFor: ['Bilinçli gezginler', 'Trend takipçileri', 'Sosyal gezginler'],
    reasonsToChoose: [
      'Japonya\'nın ilk sosyal sorumluluk oteli',
      'Lokal üreticilerden sürdürülebilir ürünler',
      'Trendy Cat Street\'e yürüme mesafesi'
    ],
  },
];

// ========== ADDITIONAL BALI HOTELS ==========
export const baliHotelsExpanded: HotelData[] = [
  {
    slug: 'como-shambhala-estate-bali',
    name: 'COMO Shambhala Estate',
    citySlug: 'bali',
    summary: 'Ubud\'un kuzeyinde wellness odaklı lüks retreat. Detoks programları ve yoga.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Yoga', 'Wellness', 'Restoran', 'Ayurveda'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    address: 'Banjar Begawan, Payangan, Gianyar, Bali',
    neighborhood: 'Ubud',
    rating: 4.9,
    reviewCount: 670,
    priceRange: { min: 25000, max: 150000, currency: 'TRY' },
    highlights: ['Wellness retreat', 'Detoks', 'Yoga'],
    suitableFor: ['Wellness arayanlar', 'Yoga tutkunları', 'Detoks'],
    reasonsToChoose: [
      'Dünyanın en iyi wellness destinasyonlarından biri',
      'Kişiselleştirilmiş detoks ve wellness programları',
      'Yağmur ormanı içinde tam gizlilik'
    ],
  },
  {
    slug: 'bulgari-resort-bali',
    name: 'Bulgari Resort Bali',
    citySlug: 'bali',
    summary: 'Uluwatu\'da uçurumlarda İtalyan tasarım ve Bali ruhu. Ultra lüks villalar.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Özel Plaj', 'Restoran', 'Bar', 'Butler Servisi'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: 'Jl. Goa Lempeh, Banjar Dinas Kangin, Uluwatu, Bali',
    neighborhood: 'Uluwatu',
    rating: 4.9,
    reviewCount: 890,
    priceRange: { min: 50000, max: 300000, currency: 'TRY' },
    highlights: ['Uçurum villalar', 'Bulgari tasarımı', 'Özel plaj'],
    suitableFor: ['Ultra lüks', 'Balayı', 'Benzersiz deneyim'],
    reasonsToChoose: [
      'Hint Okyanusu\'na bakan uçurumlarda eşsiz konum',
      'Bulgari\'nin İtalyan zarafeti ve Bali estetiği',
      'Özel funiküler ile deniz seviyesinde plaj'
    ],
  },
  {
    slug: 'mandapa-ritz-carlton-bali',
    name: 'Mandapa, a Ritz-Carlton Reserve',
    citySlug: 'bali',
    summary: 'Ayung Nehri vadisinde ultra lüks resort. Bali manevi atmosferi ve lüks birleşimi.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Yoga', 'Restoran', 'Bar', 'Rice Terrace'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    address: 'Jl. Kedewatan, Banjar Kedewatan, Ubud, Bali',
    neighborhood: 'Ubud',
    rating: 4.9,
    reviewCount: 560,
    priceRange: { min: 35000, max: 200000, currency: 'TRY' },
    highlights: ['Ayung Nehri', 'Manevi deneyim', 'Reserve konsepti'],
    suitableFor: ['Manevi arayış', 'Balayı', 'Ultra lüks'],
    reasonsToChoose: [
      'Ritz-Carlton\'un en üst segmenti Reserve',
      'Bali Hindu manevi ritüelleri ve meditasyon',
      'Ayung Nehri manzaralı özel villalar'
    ],
  },
  {
    slug: 'st-regis-bali',
    name: 'The St. Regis Bali Resort',
    citySlug: 'bali',
    summary: 'Nusa Dua\'da denize sıfır ultra lüks resort. St. Regis butler servisi ve özel lagün.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Özel Plaj', 'Lagün', 'Restoran', 'Butler Servisi'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    address: 'Kawasan Pariwisata Nusa Dua Lot S6, Nusa Dua, Bali',
    neighborhood: 'Nusa Dua',
    rating: 4.8,
    reviewCount: 1890,
    priceRange: { min: 30000, max: 180000, currency: 'TRY' },
    highlights: ['Özel lagün', 'Butler servisi', 'Nusa Dua'],
    suitableFor: ['Aileler', 'Balayı', 'Plaj tatili'],
    reasonsToChoose: [
      'Nusa Dua\'nın en prestijli adresi',
      'Her odada St. Regis butler servisi',
      'Tuzlu su lagününde özel yüzme'
    ],
  },
  {
    slug: 'ayana-resort-bali',
    name: 'AYANA Resort Bali',
    citySlug: 'bali',
    summary: 'Jimbaran\'da uçurumlarda mega resort. Rock Bar ve geniş tesis alanı.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Rock Bar', 'Özel Plaj', 'Golf', 'Kids Club'],
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'],
    address: 'Jl. Karang Mas Sejahtera, Jimbaran, Bali',
    neighborhood: 'Jimbaran',
    rating: 4.7,
    reviewCount: 4560,
    priceRange: { min: 12000, max: 60000, currency: 'TRY' },
    highlights: ['Rock Bar', 'Mega tesis', 'Jimbaran uçurumları'],
    suitableFor: ['Çiftler', 'Aileler', 'Gün batımı severler'],
    reasonsToChoose: [
      'Dünyanın en ikonik barlarından Rock Bar',
      '90 hektarlık geniş tesis alanı',
      'Jimbaran uçurumlarında eşsiz gün batımı'
    ],
  },
  {
    slug: 'mulia-resort-bali',
    name: 'The Mulia Bali',
    citySlug: 'bali',
    summary: 'Nusa Dua\'da tüm suit\'li ultra lüks resort. Infinity havuz ve özel butler.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Özel Plaj', 'Restoran', 'Bar', 'Butler Servisi'],
    images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800'],
    address: 'Jl. Raya Nusa Dua Selatan, Nusa Dua, Bali',
    neighborhood: 'Nusa Dua',
    rating: 4.8,
    reviewCount: 2340,
    priceRange: { min: 25000, max: 150000, currency: 'TRY' },
    highlights: ['Tüm suit', 'Infinity havuz', 'Butler'],
    suitableFor: ['Ultra lüks', 'Balayı', 'Özel tatil'],
    reasonsToChoose: [
      'Sadece suite odalardan oluşan özel konsept',
      'Bali\'nin en büyük infinity havuzlarından biri',
      'Mulia Spa\'da dünya standartlarında wellness'
    ],
  },
  {
    slug: 'alila-ubud-bali',
    name: 'Alila Ubud',
    citySlug: 'bali',
    summary: 'Ubud\'da pirinç terasları manzaralı butik resort. Sürdürülebilir lüks.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Yoga', 'Restoran', 'Bisiklet', 'Trekking'],
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800'],
    address: 'Desa Melinggih Kelod, Payangan, Ubud, Bali',
    neighborhood: 'Ubud',
    rating: 4.7,
    reviewCount: 1120,
    priceRange: { min: 10000, max: 45000, currency: 'TRY' },
    highlights: ['Pirinç terasları', 'Sürdürülebilir', 'Doğa'],
    suitableFor: ['Doğa severler', 'Wellness', 'Eko tatil'],
    reasonsToChoose: [
      'UNESCO koruma altındaki pirinç terasları manzarası',
      'Alila\'nın sürdürülebilir turizm yaklaşımı',
      'Yerel köylere trekking ve bisiklet turları'
    ],
  },
  {
    slug: 'capella-ubud-bali',
    name: 'Capella Ubud',
    citySlug: 'bali',
    summary: 'Ubud\'da glamping konseptinde ultra lüks kamp. Nehir kenarında çadır villalar.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Restoran', 'Yoga', 'Safari Tent', 'Adventure'],
    images: ['https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=800'],
    address: 'Keliki, Tegallalang, Ubud, Bali',
    neighborhood: 'Ubud',
    rating: 4.9,
    reviewCount: 450,
    priceRange: { min: 45000, max: 250000, currency: 'TRY' },
    highlights: ['Glamping', 'Nehir kenarı', 'Macera'],
    suitableFor: ['Macera arayanlar', 'Benzersiz deneyim', 'Doğa'],
    reasonsToChoose: [
      'Dünyanın en lüks glamping deneyimlerinden biri',
      'Wos Nehri kenarında özel çadır villalar',
      '19. yüzyıl kampçılarından esinlenen tasarım'
    ],
  },
  {
    slug: 'w-bali-seminyak',
    name: 'W Bali - Seminyak',
    citySlug: 'bali',
    summary: 'Seminyak\'ta sahil şeridinde trendy resort. Woobar ile gece hayatı ve şık tasarım.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Woobar', 'Özel Plaj', 'Restoran', 'DJ'],
    images: ['https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800'],
    address: 'Jl. Petitenget, Seminyak, Bali',
    neighborhood: 'Seminyak',
    rating: 4.6,
    reviewCount: 2890,
    priceRange: { min: 12000, max: 55000, currency: 'TRY' },
    highlights: ['Woobar', 'Trendy atmosfer', 'Beach club'],
    suitableFor: ['Genç çiftler', 'Gece hayatı', 'Trend takipçileri'],
    reasonsToChoose: [
      'Bali\'nin en ikonik beach bar\'ı Woobar',
      'Seminyak\'ın canlı gece hayatının merkezi',
      'W markasının dinamik ve eğlenceli tarzı'
    ],
  },
  {
    slug: 'hanging-gardens-bali',
    name: 'Hanging Gardens of Bali',
    citySlug: 'bali',
    summary: 'Ubud\'da yağmur ormanında çift katlı infinity havuz. Dünyanın en güzel havuzlarından biri.',
    stars: 5,
    amenities: ['Spa', 'Havuz', 'Restoran', 'Yoga', 'Trekking', 'Funiküler'],
    images: ['https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800'],
    address: 'Desa Buahan, Payangan, Ubud, Bali',
    neighborhood: 'Ubud',
    rating: 4.8,
    reviewCount: 1230,
    priceRange: { min: 20000, max: 100000, currency: 'TRY' },
    highlights: ['İkonik havuz', 'Yağmur ormanı', 'Villalar'],
    suitableFor: ['Instagram', 'Romantik tatil', 'Doğa'],
    reasonsToChoose: [
      'Dünyanın en çok fotoğraflanan havuzlarından biri',
      'Yağmur ormanı içinde özel villalar',
      'Pura Dalem Segara tapınağına yürüme mesafesi'
    ],
  },
];

// Combine all expanded hotels into a single export
export const allExpandedHotels: HotelData[] = [
  ...istanbulHotelsExpanded,
  ...antalyaHotelsExpanded,
  ...dubaiHotelsExpanded,
  ...tokyoHotelsExpanded,
  ...baliHotelsExpanded,
];

export default allExpandedHotels;
