project_id = "dpcnlhasbumemcwuggsu"

[functions.search-hotels]
verify_jwt = false

[functions.search-flights]
verify_jwt = false

[functions.get-airports]
verify_jwt = false

[functions.generate-itinerary]
verify_jwt = false

[functions.generate-blog-content]
verify_jwt = false

[functions.seo-improve-blog]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.translate-content]
verify_jwt = false

[functions.generate-blog-image]
verify_jwt = false

[functions.generate-deep-work-rota]
verify_jwt = false

[functions.generate-alt-text]
verify_jwt = false
